jscad/OpenJSCAD.org

- csg.js
- openjscad
For making 2D objects (CAG) on a laser cutter or water jet.
> Add DXF output format to the openjscad CLI

- index.html
- openjscad.js
- style.css
So, as the title says, I have made some changes to correct the size of the canvas, and added resizing of the canvas if the document size changes. The changes include:
- Changes to index.html to remove all hard coded height and width. These are now in style.css
- Changes to index.html to rename "viewer" div to "viewerContext". This corrected some confusion in style.css
- Changes to style.css to make the document 100% of the browser window. Add styles for HTML and BODY
- Changes to style.css to make "viewerContext" 100% of the BODY
- Changes to style.css to make "canvas" 100% of the viewerContext DIV
- Changes to openjscad.js to correct object references (gl... to this.gl...)
- Changes to openjscad.js to determine the size of the "viewer" div from the containerelement
- Changes to …
> Changes to correct canvas size and resizing

- index.html
- js/index.js
- js/ui-cookies.js
- js/ui-drag-drop.js
- js/ui-editor.js
- js/ui-worker.js
- js/worker-conversion.js
- min.css
- min.html
- openjscad.css
- openjscad.js
- style.css
These changes separate the JavaScript from the HTML, and create manageable pieces for the page, the editor, the drag-and-drop, etc. This will help to create further pages as well as extend functionality.
@richievos was a great inspiration, and many of his changes were bundled into these.
This is fully tested off-line, on-line, and CLI. In addition, testing was performed with Firefox, Chrome, Safari, and Opera on Mac OSX.
> Partitioning of HTML from JavaScript in Pages

- examples/balloons.jscad
- js/ui-drag-drop.js
@xosos opened an issue #106 against drag and drop, as he wasn't able to drop multiple files. The issue was with the determination of the "main" source, which was required to reside in a file named "main.jscad" or "main.js". I enhanced the logic to search for the function declaration in the files if necessary.
Should "main.scad" be allowed as well?
I also removed the hide and show of the editor pane as well. I don't think this is necessary, and showing the "main" source seems more proper to me.
I commented out the debug statements, but left those in the source.
There's a small change to the balloon example as well, adding initial values for name and data parameters. This allows the CLI script to run the example as well.
> Enhanced Determination of "main" Source

- index.html
- js/index.js
- js/jscad-function.js
- js/jscad-worker.js
- js/ui-drag-drop.js
- min.html
- openjscad.js
This is a fairly significant change, moving away from code within comments within code. The functionality is now split into jscad-worker.js (ASYNC) and jscad-function.js (SYNC). The code can now be fixed/debugged easily, and enhanced if additional functionality is required.
Note: The old async and sync functions still exist, and should be removed once the new code has been tested completely.
In addition, there are a few small changes to drag and drop to accommodate and streamline processing.
Finally, the strange global variable _includePath is now derived from the URL of script. This global is no longer required.
> Reworked JSCAD Script Processing

- README.md
- openjscad.js
This is the fix and update to the 0.4.0 release. Contents include:
-  Remove remote links and parameters before setting baseurl 
- Date change only
> Updating Master to Fix Issues with URL Parameters

- js/jscad-parseSVG.js
Changed to use PXPMM if provided on SVG element
Corrected scaling of units if viewBox is provided on SVG element
> Fixes for SVG Conversions

- csg.js
- index.html
- js/jscad-worker.js
- js/ui-drag-drop.js
- js/ui-editor.js
- openjscad.js
These changes provide more flexibility when creating the Processor and the Viewer. All "settings" have been moved into the constructors, and documented (a little). Several new functions were created to change the Viewer settings easily. Several function were updated change the Processor settings.
As a result of this work, I also added the ability to reset the perspective of the viewer to the original settings. And index.html now has a new key stroke (CRTL-RETURN) which resets the viewer.
I believe that both Processor and Viewer are now fully encapsulated, and will create another example to test the ability to use more than one Processor per page. Some small changes may be required still.
> Rework of Viewer and Processor to Support Options

- min.html
- openjscad.css
- openjscad.js
These changes were made to allow more flexibility in the layout and the styles of HTML pages. The hard coded styles were moved to the openjscad.css file. The DIV elements for errors, status, and parameters are created if not found.
Functionally, there should be no difference. All examples pass, as well as drag and drop.
> Changes to support various HTML pages

- index.html
- js/ui-drag-drop.js
This implements #111 
On iPad/iPhone, users can now select files from various "cloud" storage.
A section has been added to the HTML file to define a File selection button, which is used for "mobile" devices.
The drag and drop functionality has been enhanced to hide or show the File selection button, as well as process the list of files selected.
Note: There's no way to determine if drag and drop of FILES is supported. Most browsers support some kind of drag and drop, i.e. links, images, etc. So, based on consensus, if TOUCH is detected then the File selection is enabled (drag and drop is disabled). Not perfect but works well.
> Enhanced drag-n-drop to support mobile devices

- index.html
- js/index.js
- js/ui-editor.js
I have been using the live version of OpenJSCAD.org for a number of weeks now and repeatedly refreshed the page when intending to build / render. I also found it lengthy to repeatedly copy & paste my code in to and out of another editor in order to save.
This pull request adds the following features to the editor on the site:
- Save to and load from local storage (CTRL-S, CTRL-L)
- Download the source as a file **MyDesign.jscad** (CTRL-SHIFT-S)
- Automatically resume editing from previously saved source in local storage when visiting the page
- Update render shortcut to F5 and add mentioned shortcuts above
If there are any suggestions to improve these features, please let me know!
> Source editor workflow improvements

- openscad.js
Only .setColor() in intersection() & difference() for non-CAGs.
A further improvement would implement CAG.setColor(), but that's not here.
To see the problem this fixes, observe this works:
`function main() { return union(circle(), circle().translate([1, 0, 0])); }`
but replacing `union` with `difference` or `intersection` errors out with:
`Error in line 353: Uncaught TypeError: a[i].setColor is not a function`
This patch removes this error and results in correct-looking intersection/difference.
> Unbreak intersection() & difference() for CAGs.

- Makefile
Pretty small fix, that makes `make deinstall` actually deinstall the bin and the directory that was created on `make install`.
Nothing too major but good hygiene for any project.
> fix `make deinstall` to properly deinstall openjscad

- openjscad.js
This is a bug fix for browsers which have issues with determining that passed parameters are arrays. This fixes issues with Chrome when designs return a single CSG or CAG object. And possibly other browsers.
> Corrected determination of array parameters

- src/jscad/processor.js
- src/jscad/rebuildSolid.js
- src/ui/examples.js
Download all files directly (rather than tunneling through a proxy
server) to remove dependence on running a special server. This is
useful, for example, when providing a remote link to a Github repository
for a project that isn't a single file. Remote projects (with includes)
are currently limited to someone running a special server; this ensures
effectively any remote file host is usable instead.
We also store the include file base path separately now since it should
be resolved to the host of the primary file rather than the host serving
up the OpenJSCAD viewer.
This also cleans up the `include` logic a bit: currently regex parsing
is used for replacement which isn't safe: i.e., it's possible for the
regex to match unnecessarily. It's also the case that multiple includes
for the same …
> Add support for include() in remote files; remove  need for proxy.

- README.md
- src/ui/examples.js
- src/ui/index.js
This PR adds a possible fix & upgrade for #274 
- add standard (normal) url param parsing instead of the '#' based remote document param 
- adds back and cleans up previous # + proxy
- proxy can be disabled by setting proxyURL to undefined
- removed url clearing so that parameters & uris stay and are clear
- fleshed out readme
This means you can use things like: 
- http://localhost:8081/?uri=http://www.thingiverse.com/download:164128 
- http://localhost:8081/?uri=examples/example001.jscad (works)
> fix(remote loading)

- src/jscad/processor.js
This PR implements #291 : it makes 'live updates' for parameters much more pleasant to look at 
**BEFORE:**
**AFTER:**
> feat(processor/viewer): do not clear viewer until new 3D mesh is ready

- remote.pl
From Rene...
Here the current remote.pl 0.005 which limits to http/https (quits quitely if not) only and a few file extensions, to add new file extension should be simple. In case an invalid file is tried to download an JSON error message is return (which you might catch in the JS code and show it the user): { "error": "only amf, js .. supported" }
> Limit URL to http or https

- README.md
- Changed `npm link ../csg.js/ @jscad/csg` to `npm link ../csg.js`.
I'm not sure what the old recipe was supposed to mean (`npm help link`
doesn't mention that usage), but it gave me errors when I tried it
(npm v3.10.10).  The new recipe is what the help page describes,
and it works for me.
- Changed the `git clone` urls to the ones advertised on the respective
github pages, which use https (the old ones weren't working for me).
- Added explicit recipe for making the main repo live-updating (`npm link`),
and separated out the csg.js-specific commands into a distinct section
for clarity.
> Fix and clarify npm link instructions in README.md.

- src/ui/viewer/jscad-viewer-lightgl.js
- src/ui/viewer/jscad-viewer.js
My goal is to be able to use canvas.toDataURL() from the viewer. 
To do that, we need to be able to pass `{preserveDrawingBuffer: true}` as the `options` to
```gl = canvas.getContext('webgl', options);``` [here](https://github.com/jscad/OpenJSCAD.org/blob/master/src/ui/viewer/lightgl.js#L1137)
This PR is the plumbing which passes the gl options through. So we can create a `new Viewer(viewerdiv, { glOptions: {preserveDrawingBuffer: true} })`
> plumb GL options through viewer

- src/core/convertToSolid.js
- src/io/formats.js
This replaces the last remaining instanceOf CSG/CAG calls (which are dangerous, as objects using different versions of CSG.js will end up NOT having the correct type detected) 
They now use the helper functions isCAG/isCSG which use very basic 'duck typing' (ie checking the internal fields of the objects).
> fix(instanceOf): replaced remaining instanceOF CA/SG 

- packages/cli/cli.js
- packages/cli/cli.test.js
- packages/cli/generateOutputData.js
- packages/cli/package.json
- packages/core/io/formats.js
- packages/core/package.json
- packages/web/package.json
- packages/web/src/io/conversionWorker.js
This PR adds support for dxf files as inputs, thanks to the great work in @jscad/io by @z3dev !
It also adds minor tweaks to the CLI to make handling of input formats easier
> feat(dxf input support): add Dxf deserializer to support dxf input files

- packages/cli/package.json
- packages/core/package.json
- packages/web/package.json
* bumped dependency versions to include svg export fix
> fix(svg-serializer): updated @jscad/io version to add fix for broken svg export

- packages/desktop/package.json
For desktop: Pins electron builder version, to avoid build issues for windows release
> chore(pkg): desktop: pinned electron builder to avoid building issues for windows

- packages/web/src/ui/dragDrop/walkFileTree.js
Chrome, at least on ChromOS, puts null's in the DataTransferItem array.
This causes "Uncaught TypeError: Cannot read property
'webkitGetAsEntry' of null" when you drag a file on to the drop zone.
I'm not sure why, but the nulls need to be skipped.
Closes issue #331
Signed-off-by: James Hightower <jamesh@qtime.com>
> Error uploading file on Chrome OS #331

- packages/web/package.json
- packages/web/src/ui/flow/design.js
The serialize-to-js module was missing from the dependencies, which is required as part of the web flow functionality. As such, the require also had to change, as the module has recently gone through some API changes.
> Upgraded to latest version of module serialize-to-js

- .gitignore
- coverage_reports.html
- package.json
- packages/core/package.json
- packages/io/amf-deserializer/package.json
- packages/io/amf-serializer/package.json
- packages/io/dxf-deserializer/package.json
- packages/io/dxf-serializer/package.json
- packages/io/io-utils/package.json
- packages/io/json-deserializer/package.json
- packages/io/json-serializer/package.json
- packages/io/obj-deserializer/package.json
- packages/io/stl-deserializer/package.json
- packages/io/stl-serializer/package.json
- packages/io/svg-deserializer/package.json
- packages/io/svg-serializer/package.json
- packages/io/x3d-serializer/package.json
- packages/modeling/package.json
These changes enables coverage reports for packages with test suites.
The coverage reports can be viewed by opening the "coverage_reports.html" file in the project directory.
> V2 : Enable coverage reports

- packages/cli/src/generateOutputData.js
- packages/core/code-loading/transformSources.js
- packages/core/code-loading/webRequire.test.js
- packages/core/io/registerExtensions.js
- packages/io/amf-deserializer/deserialize.js
- packages/io/amf-deserializer/index.js
- packages/io/amf-deserializer/tests/instantiate.test.js
- packages/io/amf-deserializer/tests/translate.test.js
- packages/io/amf-deserializer/translate.js
- packages/io/dxf-deserializer/index.js
- packages/io/dxf-deserializer/tests/test-2d-entities.js
- packages/io/dxf-deserializer/tests/test-2d-translation.js
- packages/io/dxf-deserializer/tests/test-3d-entities.js
- packages/io/dxf-deserializer/tests/test-3d-translation.js
- packages/io/dxf-deserializer/tests/test-dxf-versions.js
- packages/io/dxf-deserializer/tests/test-dxf.js
- packages/io/obj-deserializer/index.js
- packages/io/obj-deserializer/tests/instantiate.test.js
- packages/io/obj-deserializer/tests/translate.test.js
- packages/io/stl-deserializer/index.js
- packages/io/stl-deserializer/tests/instantiate.test.js
- packages/io/stl-deserializer/tests/translate.test.js
- packages/io/svg-deserializer/index.js
- packages/io/svg-deserializer/tests/inkscape.test.js
- packages/io/svg-deserializer/tests/instantiate.test.js
- packages/io/svg-deserializer/tests/translate.test.js
These changes update the various deserializers to:
- deserialize(options, source)
- new options.filename
- corrected options.output to accept only 'script' or 'geometry'
And of course, updating CLI and CORE code to use these new standards.
> V2 : Fix Deserializers

- packages/utils/array-utils/flatten.test.js
- packages/utils/array-utils/head.test.js
- packages/utils/array-utils/index.js
- packages/utils/array-utils/nth.test.js
- packages/utils/array-utils/package.json
- packages/utils/array-utils/toArray.test.js
These changes complete a test suite for the array-utils module, covering all functions.
In addition, logic has been changed to use Array.isArray() to determine when a array is provided as a parameter. Document strings have also been improved.
> V2 : test array utils

- packages/io/stl-deserializer/index.js
- packages/modeling/src/primitives/polyhedron.js
- packages/modeling/src/primitives/polyhedron.test.js
These changes add support for colors (arrays) to polyhedron. The colors are applied to each face (polygon) of the polyhedron (geom3).
The reason behind these changes is that the several deserializers use polyhedron to produce geometries.
> V2 : enhanced polyhedron to accept an array of colors

- packages/modeling/src/operations/booleans/fromFakePolygons.js
There was a issue within fromFakePolygons() as the dynamic EPS (snaping of points) was producing sides with the same points, e.g. [[1, 2], [1, 2]]. This causes the geom2 to have a zero (0) length side, and subsequent functions using the geom2 fail.
**This is a small fix but IMPORTANT.**
> V2 : fix fromFakePolygons

- packages/core/code-evaluation/instanciateDesign.js
- packages/core/code-loading/transformSources.js
This pull request contains a couple of fixes to the core library.
**instantiateDesign()** was properly converting returned solids toArray() but designs can return arrays, or even arrays of arrays. flatten() was added to handle these cases.
**transformSource()** was transforming everything found in the filesAndFolders. all the children (STL, etc. files) were being converted to scripts, causing designs to fail. the transforming of children was removed, as specific file types can be converted directly to geometry via require().
sadly, test cases are not possible for the core library. sigh.
> V2 fix core

- packages/cli/cli.conversions.test.js
- packages/cli/src/generateOutputData.js
- packages/core/code-evaluation/rebuildGeometryCli.js
These changes adjust the logic in rebuildGeometryCli() to ONLY use webRequire() when a conversion to JSCAD source happens, e.g. STL translation. The opposite is also true, the logic ONLY uses require() in normal cases.
Fixes #504 for the CLI only.
Fixes conversions from STL to DXF, etc. (test case has been enabled)
I always wondered why webRequire() was used by rebuildGeometryCli(), and now I understand. There's a special case when external formats are converted in-memory, which webRequire() handles nicely.
> V2 : fix rebuild geometry for cli

- packages/io/svg-deserializer/index.js
- packages/io/svg-deserializer/shapesMapGeometry.js
- packages/io/svg-deserializer/tests/instantiate.test.js
While testing direct require of external formats, I found that the SVG deserializer had some issues in instantiating shapes. These fixes correct those, and enhance the test suite to test those code branches.
> V2 : fix svg deserializer

- packages/io/svg-serializer/index.js
- packages/io/svg-serializer/tests/geom2.test.js
- packages/io/svg-serializer/tests/path2.test.js
These changes correct the orientation of SVG shapes. The orientation is now the same as designs / rendering. Test suites have been updated as well.
I noticed this a while back and finally got around to fixing this.
> V2 : fix svg serialize

- packages/modeling/src/maths/OrthoNormalBasis.js
- packages/modeling/src/maths/plane/fromPointsRandom.js
- packages/modeling/src/maths/plane/transform.js
- packages/modeling/src/maths/vec2/distance.js
- packages/modeling/src/maths/vec2/length.js
- packages/modeling/src/maths/vec2/normalize.js
- packages/modeling/src/maths/vec2/normalize.test.js
- packages/modeling/src/maths/vec3/angle.js
- packages/modeling/src/maths/vec3/angle.test.js
- packages/modeling/src/maths/vec3/distance.js
- packages/modeling/src/maths/vec3/index.js
- packages/modeling/src/maths/vec3/length.js
- packages/modeling/src/maths/vec3/normalize.js
- packages/modeling/src/maths/vec3/normalize.test.js
- packages/modeling/src/maths/vec3/orthogonal.js
- packages/modeling/src/maths/vec3/orthogonal.test.js
- packages/modeling/src/operations/hulls/hullChain.test.js
- packages/modeling/src/primitives/cylinderElliptic.js
These changes bring the logic of vec2 and vec3 upto the same logic as glmatrix. Most are small changes, but improve precision as well as speed.
vec3.random() was renamed to vec3.orthogonal() to better reflect the functionality. (There's nothing random about this function!)
> V2 fix vecs

- lerna.json
- package.json
- packages/modeling/src/measurements/measureArea.js
- packages/modeling/src/measurements/measureBoundingBox.js
- packages/modeling/src/measurements/measureEpsilon.js
- packages/modeling/src/measurements/measureVolume.js
- packages/modeling/src/operations/booleans/intersectGeom2.js
- packages/modeling/src/operations/booleans/retessellate.js
- packages/modeling/src/operations/booleans/subtractGeom2.js
- packages/modeling/src/operations/booleans/unionGeom2.js
These changes tune the comparison of plane normals, which assists retesselate.
There are also changes to the measurements, caching calculated values as object attributes. For example, object.volume, etc. These are expected to improve the performace of boolean operations.
Additional testing was completed with both CLI and WEB applications.
> V2 : tune retesselate

- packages/core/code-evaluation/instanciateDesign.js
- packages/web/src/ui/flow/design.js
These changes update the serialization of objects in the WEB UI.
The advantages are:
- all objects are serialized, not just JSCAD objects
- all attributes are serialized, not just JSCAD object data structures
- rendering of polygons with individual colors
The disadvatages are:
- increased memory useage, as JSON strings require more memory
> V2 : Web : serialize object using JSON

- packages/modeling/src/geometries/geom2/transform.js
- packages/modeling/src/geometries/geom2/transform.test.js
- packages/modeling/src/geometries/geom3/transform.js
- packages/modeling/src/geometries/geom3/transform.test.js
- packages/modeling/src/geometries/path2/transform.js
- packages/modeling/src/geometries/path2/transform.test.js
Fixes #520. Warning: this is a substantial breaking change!
New matrices applied via the transform() functions of geom2, geom3, and
path2 should multiply with the new matrix on the left. That is, instead
of geom.transform = geom.transform * new_transform, it should be
geom.transform = new_transform * geom.transform.
Before this change, calls to transform() are effectively applied
Last-In-First-Out (stack order). This can lead to strange circumstances
like where a caller tries to move a shape long the X axis, but since
previous code already pushed a "rotate around the Z axis" matrix onto the
"stack", the call to translateX() actually translates along the Y axis,
which is clearly not the user's intent.
Fixed tests, and also changed them a bit to translate differenly along
different axes. …
> Fixes #520. Warning: this is a substantial breaking change!

- packages/io/svg-deserializer/index.js
- packages/io/svg-deserializer/shapesMapGeometry.js
- packages/io/svg-deserializer/shapesMapJscad.js
- packages/io/svg-deserializer/tests/instantiate.test.js
This adds a `segments` argument to the SVG Deserializer. It gets passed down to any curves, specifically: ellipses, circle, rounded rectangles and bezier curves using the existing `segments` argument in each of the primitives. This works both for the script and path output.
The tests add a case for each of these testing the increase of segments. In the case of ellipses and circles, the default used (32) to be different from the default for bezier curves (16). Now, since there's only one argument to control both and the new default is 16, the ellipses, circles and rounded rectangles created through the SVG deserializer will have `segments=16`. 
This PR comes after the discussion in issue #681
> Add support for segments in SVG Deserializer

- packages/web/remote.php
- packages/web/src/index.js
- packages/web/src/sideEffects/dragDrop/index.js
- packages/web/src/sideEffects/http/index.js
- packages/web/src/sideEffects/localFs/walkFileTree.js
- packages/web/src/ui/flow/design.js
- packages/web/src/ui/flow/flowOut.js
- packages/web/src/ui/views/examples.js
- packages/web/src/utils/urlUtils.js
These changes fix the loading of designs from remote URLs, using the webserver as a proxy cache for the contents of the URLs. This allows:
- URL addresses containing hashes; http://jscad.xyz#http://external.com/data/design.js
- URL addresses containing queries; http://jscad.xyz#uri=http://external.com/data/design.js
- drag and drop of URLs
Testing was performed on MacOS and Windows 10, across the following browsers
- Safari
- Chrome
- Firefox
- Edge
- Opera
Note: The installation of the backend process is required to use this functionality. An additional note was added to the [V2 Summary of Changes](https://openjscad.org/dokuwiki/doku.php?id=changes_v2).
Fixes #688 
> V2 : fix loading of designs from remote URLs

- packages/web/src/sideEffects/localFs/index.js
These changes correct the file system watcher, which was hard-coded to 5000 ms intervals. These changes calculate a dynamic delay based on the performance of the comparison (old vs new filesystem), which can take significant cycles for large projects.
For small projects, the minimum delay will take affect; 1000 ms / 1 second.
Fixes #710 
Fixes #661 
Additional testing was completed against Safari, FireFox, and Chrome on MacOS.
> fix(web): changed the file system watcher to use setTimeout(), and calculate dynamic delays

- packages/io/svg-deserializer/index.js
- packages/io/svg-deserializer/shapesMapGeometry.js
- packages/io/svg-deserializer/svgElementHelpers.js
- packages/io/svg-deserializer/tests/instantiate.test.js
These changes enhance the SVG deserializer to support mirror transforms. 
Some small changes were also made:
- corrected order of transforms
- corrected translate transforms with a single value
- added conversion of X / Y attributes on GROUP / USE entities into translate transforms 
- corrected size of rectangles when instantiating to objects
Fixes #704 
Fixes #523 
Additional testing with the SVG sample files was also conducted via the WEB UI.
> V2 : enhance SVG deserializer for mirror transforms

- packages/modeling/src/geometries/poly2/arePointsInside.js
- packages/modeling/src/geometries/poly2/arePointsInside.test.js
There were some issues found while testing offset versus expand operations.
The root of the issue was the isPointInside function of poly2. After trying several variations of the 'winding test', the function was re-implemented using the 'crossing test'. This corrected the issues found, and further testing was fine as well.
> V2 : re-implemented poly2.isPointInside to correct issues

- packages/web/css/codemirror.css
- packages/web/css/demo.css
- packages/web/data/keybindings.json
- packages/web/locales/de.json
- packages/web/locales/en.json
- packages/web/locales/fr.json
- packages/web/locales/ja.json
- packages/web/src/index.js
- packages/web/src/sideEffects/http/index.js
- packages/web/src/ui/flow/shortcuts.js
- packages/web/src/ui/views/editor2.js
- packages/web/src/ui/views/shortcuts.js
These changes enable the editor for single file designs. The editor is based on the CodeMirror library, which supports various languages and options. This initial version has support for:
- javascript syntax only
- line numbers
There's no support for projects, so a small message is shown as a comment.
There's no support for conversions from STL to JSCAD source, etc, so a small message is shown as a comment.
Additional testing performed manually across browsers.
> V2 : initial implementation of the built-in editor

- packages/core/src/parameters/applyParameterDefinitions.js
- packages/modeling/src/operations/extrusions/slice/calculatePlane.js
- packages/modeling/src/operations/extrusions/slice/calculatePlane.test.js
These changes correct the calculation of planes for slices, where the slice is a complex shape. Additional tests have been added as well.
Fixes #749 
There's an additional fix to the core library which I found while working on the VUE components. This fix allows parameter values to be used even if the design does not define the parameter. In other words, designs should not be required to define parameters via getParameterDefinitions(). The checks should only be performed IF there's a definition.
> V2 : fix extrude

- CONTRIBUTING.md
- README.md
- jsdoc/tutorials/01_gettingStarted.md
- packages/cli/README.md
- packages/core/README.md
- packages/desktop/README.md
- packages/examples/README.md
- packages/io/amf-deserializer/README.md
- packages/io/amf-serializer/README.md
- packages/io/dxf-deserializer/README.md
- packages/io/dxf-serializer/README.md
- packages/io/gcode-deserializer/README.md
- packages/io/io-utils/README.md
- packages/io/io/README.md
- packages/io/json-deserializer/README.md
- packages/io/json-serializer/README.md
- packages/io/obj-deserializer/README.md
- packages/io/stl-deserializer/README.md
- packages/io/stl-serializer/README.md
- packages/io/svg-deserializer/README.md
- packages/io/svg-serializer/README.md
- packages/io/x3d-serializer/README.md
- packages/modeling/README.md
- packages/utils/array-utils/README.md
- packages/web/README.md
- packages/web/src/ui/views/help.js
These changes update the links in documentation to the new website; www.openjscad.xyz
There were some small changes to correct documentation as well. All good.
> docs(all): updated links to new website

- jsdoc.json
- packages/cli/cli.conversions.test.js
- packages/cli/package.json
- packages/core/src/code-loading/webRequire.js
These changes expose the array utilities. Designs can now require(''@jscad/array-utils) and use the available functions. This includes both CLI and WEB applications. (Part 2 of the re-organization of array utilities)
In addition, documentation for the API will be generated going forward.
NOTE: DO NOT SQUASH AS THERE ARE MULTIPLE COMMITS
Additional testing of the WEB application was performed manually.
> Expose array utils

- packages/utils/regl-renderer/src/controls/orbitControls.js
- packages/web/src/ui/views/viewer.js
After repeated attempts to fix issues with BIG designs( #833 ) , I discovered that the orbitControls returns an indication that the camera position was moved.
After correcting that logic, I came up with an alternative set of changes to the WEB UI viewer. The changes seem reasonable, and based on previous changes from @hrgdavor 
Tested on Firefox, Chrome, and Safari
> Another attempt at fixing rendering

- packages/web/src/ui/views/viewer.js
Small change... BIG performance boost, especially with large designs.
Tested with Firefox, Chrome, and Safari
> fix(web): replaced JSON comparisons with ID comparisons in viewer

- packages/modeling/src/operations/booleans/index.js
- packages/modeling/src/operations/booleans/scission.js
- packages/modeling/src/operations/booleans/scission.test.js
- packages/modeling/src/operations/booleans/scissionGeom3.js
These changes add a new function to the booleans, called scission(). This new function cuts/divideds/scissions the given geometry into component pieces.
This is useful to pull apart larger designs into pieces, especially STL mesh imports. As well as special times when the results of boolean operations need to be split into pieces. See #517 splitting of solid into pieces 
BIG THANKS to @giboneet for the initial implementation.
> feat(modeling): new scission() function added to booleans

- .travis.yml
- packages/modeling/src/measurements/measureArea.js
- packages/modeling/src/measurements/measureBoundingBox.js
- packages/modeling/src/measurements/measureEpsilon.js
- packages/modeling/src/measurements/measureVolume.js
These changes update the measurements to use caches (WeakMap) instead of setting attributes on geometries. Previous performance tests have shown that the caches are just as fast as setting attributes.
NOTE: This is part of the effort of support users that want to set attributes, such as name or color.
Changes based on a previous PR #738 by @ahdinosaur
> reorg(modeling): changed to use caches (WeakMap) for measurements

- packages/web/src/ui/views/viewer.js
Upon testing the latest changes to master, an issue was found during testing Safari 12.0.2 (old version). The call to canvas.getContext() was returning 'null' rather then throwing an exception. This created an unusable canvas element.
https://en.wikipedia.org/wiki/Safari_(software)#Safari_15
These changes check the result of getContext(), which should allow older versions of browsers to detect the context correctly.
These changes have been tested with:
- Safari 12.0.2 Mac OS 10.14.2 and Safari 14.1.2 on Mac OS 10.14.6 (latest)
- Firefox 91.0.2
- Chrome 92.0.4515
- Explorer 92.0.902
> fix(web): enhanced createContext() for older browsers

- packages/io/svg-deserializer/tests/instantiate.test.js
- packages/modeling/src/geometries/path2/appendArc.js
- packages/modeling/src/geometries/path2/appendArc.test.js
- packages/modeling/src/geometries/path2/concat.js
- packages/modeling/src/geometries/path2/concat.test.js
fixes #912 
there is duplicate point at the joint, but not 100% equal `[1, -3]` vs `[0.9999999999999978, -3.0000000000000018]`
First issue is that path2.concat does not remove duplicate point when adding paths
Second issue is that appendArc does not produce the exact same endpoint as user asked for.
On route is to fix equality check using epsilon, and other is to force appendArc to respect the desired endpoint.
This PR  forces appendArc to respect the desired endpoint.
> Fix 912 concat and appendArc

- packages/modeling/src/maths/utils/clamp.d.ts
- packages/modeling/src/maths/utils/clamp.js
- packages/modeling/src/maths/utils/index.d.ts
- packages/modeling/src/maths/utils/index.js
- packages/modeling/src/maths/utils/quantizeForSpace.d.ts
- packages/modeling/src/maths/utils/quantizeForSpace.js
- packages/modeling/src/maths/vec2/rotate.js
- packages/modeling/src/maths/vec2/rotate.test.js
I found this little bug while looking at some examples.
In addition, clamp and quantitzeForSpace were dropped from math/utils as these functions are not used / supported.
> fix(modeling): corrected vec2.rotate, and enhanced test cases

- packages/io/dxf-serializer/index.js
I was exporting my jscad designs with color, and everything was working except the color black (also near-black colors since dxf is paletted)
For example:
```
const { colorize, cssColors } = require('@jscad/modeling').colors
const { cuboid } = require('@jscad/modeling').primitives
function main() {
return colorize([0, 0, 0], cuboid({}))
}
module.exports = { main }
```
Load the js directly into jscad and the color works:
But if you export it to a DXF file and then open that DXF file in jscad you see:
Investigation showed that `getColorNumber` in the [serializer](https://github.com/jscad/OpenJSCAD.org/blob/master/packages/io/dxf-serializer/index.js#L465) was searching from 0 to 255 through the color index. However the [deserializer](https://github.com/jscad/OpenJSCAD.org/blob/master/packages …
> Fix DXF serialization for near-black colors

- packages/modeling/src/geometries/poly3/isConvex.js
- packages/modeling/src/geometries/poly3/measureArea.js
- packages/modeling/src/geometries/poly3/measureArea.test.js
- packages/modeling/src/geometries/poly3/plane.js
- packages/modeling/src/maths/plane/fromPoints.js
- packages/modeling/src/maths/plane/fromPoints.test.js
- packages/modeling/src/operations/expansions/expand.test.js
- packages/modeling/src/operations/modifiers/snapPolygons.test.js
I made a new PR so that the change to `plane.fromPoints` could be considered separately from #952. In my opinion #952 should be closed in favor of this PR, but I will leave both open for discussion.
This is a fix for #951 "faces are lost during generalize({snap: true}, ...)".
There is a bug in `plane.fromPoints` which returns an undefined plane in the case where the first three vertices are co-linear. This can be demonstrated with:
```js
const { plane } = require("@jscad/modeling").maths
console.log("plane", plane.fromPoints(plane.create(),
[ 0, 0, 0 ],
[ 1, 0, 0 ],
[ 2, 0, 0 ],
[ 0, 1, 0 ],
))
```
```js
plane [0, 0, 0, 0]
```
The problem is that jscad takes the first three vertices and computes the vertex normal for only `vertices[1]`. This is not always defined though (for example when …
> fix(modeling): compute planes from average of all vertex normals

- packages/modeling/src/primitives/index.d.ts
- packages/modeling/src/primitives/index.js
- packages/modeling/src/primitives/triangle.d.ts
- packages/modeling/src/primitives/triangle.js
- packages/modeling/src/primitives/triangle.test.js
This is a new primitive for constructing triangles. The algorithm is based on a previous set of changes to the OLD CSG library by @ghost, and comes from a [discussion of triangles at MathIsFun](https://www.mathsisfun.com/algebra/trig-solving-triangles.html)
The inclusion of a triangle primitive is a bit controversial but for general users, triangles are one of the basic shapes, and calculating the points of a triangle is not always straight forward.
> feat(modeling): new triangle primitive

- packages/cli/cli.conversions.test.js
- packages/cli/cli.js
- packages/cli/cli.parameters.test.js
- packages/cli/src/env.js
- packages/cli/src/generateOutputData.js
- packages/cli/src/parseArgs.js
- packages/cli/src/writeOutput.js
I noticed there was a duplicate regex check in the cli `parseArgs` function. This PR removes the duplicate, and fixes all lint warnings within the cli package.
> refactor(cli): linting the cli package

- packages/web/src/ui/views/designParameters.js
There is a UI bug when a user provides malformed parameter definitions. An exception is thrown internally, but the UI gets stuck with the message:
> processing, please wait
This PR catches exceptions thrown inside the `designParameters` function. If an exception is thrown, it gets added to the `status` object so it can be displayed to the user. After applying this PR, the user message becomes more helpful:
> ERROR: Definition of choice parameter (tooling) should include a 'values' parameter
Example script:
```js
const { cuboid } = require("@jscad/modeling").primitives
function getParameterDefinitions() {
return [{name: "tooling", type: "choice", caption: "Tooling"}] // Oops forgot "values"
}
function main(params) {
return cuboid({})
}
module.exports = { getParameterDefinitions, main }
```
> fix(web): handle parameter definition exceptions

- jsdoc.json
- packages/io/svg-serializer/README.md
- packages/io/svg-serializer/index.js
- packages/io/svg-serializer/tests/geom2.test.js
- packages/io/svg-serializer/tests/path2.test.js
These changes improve the 'rendering' of designs exported to SVG. 
- set defaults for fill, fill-rule, stroke-width at the SVG level
- remove above from path serialization
- corrected fill color for continuous paths (geom2)
- added support for special attributes; id and class
> Improve svg rendering

- packages/io/test/helpers/nearlyEqual.js
- packages/io/x3d-deserializer/tests/helpers/Rotation4.js
- packages/modeling/src/maths/mat4/fromRotation.js
- packages/modeling/src/maths/mat4/rotate.js
- packages/modeling/src/maths/vec2/length.test.js
- packages/modeling/src/maths/vec3/angle.js
- packages/modeling/src/maths/vec3/angle.test.js
- packages/modeling/src/maths/vec3/length.test.js
- packages/modeling/src/primitives/geodesicSphere.js
- packages/modeling/test/helpers/nearlyEqual.js
This PR changes `Math.sqrt(x*x + y*y + z*z)` into `Math.hypot(x, y, z)`.
See [MDN: Math.hypot](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/hypot) for details.
Math.hypot has benefits of: not overflowing on large numbers, more accurate floating point math for small numbers, and generally nicer to read. It seems wise to code defensively, to avoid as many floating point bugs as possible.
I added a test case to demonstrate the problem.
> refactor(modeling): Use hypot instead of sqrt

- packages/modeling/src/geometries/geom2/toOutlines.js
The `toEdges` function inside `geom2.toOutlines` includes a quadratic runtime loop to find unique vertices. I re-wrote the function to use a map so that it can run in linear time.
For a circle with 100 segments this reduces runtime from 0.9ms to 0.4ms (2x speedup). 
For a circle with 1000 segments this reduces runtime from 12ms to 2ms (6x speedup). 
For a circle with 10000 segments this reduces runtime from 150ms to 16ms (9x speedup). 
For a circle with 50000 segments this reduces runtime from 4400ms to 90ms (50x speedup). 
For a circle with 100000 segments this reduces runtime from 16000ms to 160ms (100x speedup). 
This helps performance more as the complexity of the design increases. But it is also still faster on small geometry.
Performance test code:
```js
const jscad = …
```
> refactor(modeling): linear runtime toOutlines

- packages/modeling/src/operations/hulls/hullPath2.js
- packages/modeling/src/operations/hulls/hullPath2.test.js
- packages/modeling/src/operations/hulls/hullPoints2.test.js
The function `hullPath2` has a routine to find unique vertices which was implemented with a quadratic array loop. I re-wrote the function to use a map so that it can run in linear time.
With 100 segments this reduces runtime from 2.3ms to 0.9ms (2.5x speedup).
With 1000 segments this reduces runtime from 23ms to 4.5ms (5x speedup).
With 10000 segments this reduces runtime from 750ms to 34ms (22x speedup).
With 50000 segments this reduces runtime from 11500ms to 140ms (80x speedup).
With 100000 segments this reduces runtime from 45000ms to 290ms (150x speedup).
Performance test code:
```js
const jscad = require('@jscad/modeling')
const { geom2, path2 } = jscad.geometries
const { hull } = jscad.hulls
const { circle } = jscad.primitives
const { translate } = jscad.transforms
const main = () …
```
> perf(modeling): linear unique points in hullPath2

- packages/modeling/src/operations/expansions/expand.test.js
- packages/modeling/src/operations/expansions/expandShell.js
There is a bug in [expandShell.js](https://github.com/jscad/OpenJSCAD.org/blob/b06288af2fe8f7b007e4b10eac413c74bd6c1bfa/packages/modeling/src/operations/expansions/expandShell.js#L31) where the edge check in findIndex is always false, because it is comparing an edge to a vertex.
The result of that bug is that two cylinders are added to the expansion for each edge, instead of just one. Two cylinders on each edge is unnecessary and slows the computation down. This new code produces cleaner geometry too.
I also changed the functions to avoid linear searches for unique vertices and edges. Actually that's where I started, I only noticed the bug after I accidentally fixed it.
The following example (which is a real test from [expand.test.js](https://github.com/jscad/OpenJSCAD.org/blob/c8a37ad6430 …
> perf(modeling): expand performance and bug fix

- packages/modeling/src/geometries/geom2/index.js
- packages/modeling/src/geometries/geom3/index.js
- packages/modeling/src/geometries/index.js
- packages/modeling/src/geometries/path2/index.js
- packages/modeling/src/geometries/poly2/index.js
- packages/modeling/src/geometries/poly3/index.js
I find it hard to remember the differences between geom, paths, and polygons. So I made some docs that makes for a easy reference. I put it in the jsdoc so that it would appear in the API Reference. If you think this belongs elsewhere, let me know.
> docs(modeling): add docs describing geometries, paths, and polys

- packages/utils/regl-renderer/demo.html
This is very small quality of life change for the demo.html
I have removed `preventDefault` from mouseup and mousedown as it is note required for proper function of orbit controls.
I had to do this in new prototype to be able to have a functioning popup-menu. Without this, opening the menu and then clicking on the 3d view (canvas) the popup menu would not hide.
> quality of life change for demo.html

- .travis.yml
- packages/core/src/code-evaluation/rebuildGeometry.js
- packages/core/src/code-evaluation/rebuildGeometryWorker.js
- packages/core/src/code-loading/webRequire.js
- packages/web/css/demo.css
- packages/web/src/sideEffects/worker/index.js
- packages/web/src/ui/flow/design.js
- packages/web/src/ui/views/parameterControls.js
- packages/web/src/ui/views/status.js
A little background on these changes.
The current error handing is kind of broken (See the first set of screen shots.) There are many reasons for the really poor messages, but basically errors are propagating from web-worker thread to main thread via a DOM event called [ErrorEvent](https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent). The information propagated is incomplete or irrelevant. And of course, important information about the real error is lost immediately.
These changes do several things.
First, the core library was enhanced (not really API breaking changes) to catch all errors (both evaluation and runtime errors), and correctly report the error back via the callback. This is NEW functionality, and may break applications that are catching the DOM ErrorEvent.
Second, the …
> Improve error handling

- packages/examples/core/extrusions/nutsAndBolts.js
One of the most important mechanical building blocks are: bolts, nuts, screws, etc. Some of the most popular generative models on thingiverse are screw generators.
Have you ever tried making one in JSCAD? It's actually kind of tricky. So I took a shot at writing my own.
Initially I tried to use `extrudeLinear` with a `twistAngle` but that results in ugly and invalid geometry. The reason is that the wall faces get stretched as it rotates around. Instead I use `extrudeFromSlices` directly, and I carefully generate each slice by hand, so that the wall faces all line up.
I added this as an example model, so that hopefully users might find it helpful.
> Nuts and Bolts example

- packages/modeling/src/operations/extrusions/extrudeFromSlices.js
- packages/modeling/src/operations/extrusions/slice/repair.js
- packages/modeling/src/operations/extrusions/slice/repairSlice.js
Faster performance in `repairSlice` function by using a `Map` instead of an object `{}`.
This gives a ~18% performance improvement on 50k segment geometries inside the `repairSlice` (105ms -> 85ms).
> perf(modeling): use Map instead of {} for repairSlice

- packages/modeling/src/geometries/geom3/applyTransforms.js
- packages/modeling/src/maths/mat4/isMirroring.js
This one has been sitting around for awhile. Basically, mat4.isMirroring() was using vec3 functions to calculate cross / dot values. Now, the math is done directly within isMirroring, eliminating vec3 allocations and math.
**The performance of geom3.applyTransforms() improves 7% across the board.**
I tested manually as well, loading designs, previous issues, etc. Everything looks fine, even those designs using mirror transforms.
> perf(maths): reworked mat4 isMirroring to use pure math, eliminating vec3 creation

- packages/examples/parameters/gear.js
Very small change.
I was looking at the one of the originator repos of jscad, and found a pull request that changed the Involute Gear example which still exists in JSCAD.
From the pull request by @LunsTee [Update gears.jscad #93](https://github.com/joostn/OpenJsCad/pull/93):
> Existing code picks points on involute curve with uniform angle steps. This gives small steps on the curve close to the base circle, and larger steps away, with larger steps deviating more from the involute curve.
> 
> Deviation goes with angle*(angle step)^2. Taking the angle proportional to (i/resolution)^2/3 keeps deviation uniform, making the most out of the steps available.
OLD:
NEW:
> uniform segments for involute gear example

- packages/modeling/src/colors/colorize.d.ts
- packages/modeling/src/geometries/geom2/type.d.ts
- packages/modeling/src/geometries/geom3/type.d.ts
- packages/modeling/src/geometries/path2/type.d.ts
- packages/modeling/src/geometries/poly3/type.d.ts
- packages/modeling/src/geometries/types.d.ts
This is an attempt to improve the JSCAD geometry type definitions. See discussion from #1086
I made a few proposed changes:
- Changed geometries to not "extend" type `Colored`
- But all geometries have an _optional_ `color` field
- Changed `Colored` to _require_ that a color be present.
- Changed `Colored` from a type to an interface
- Defined a new `type Color = RGA | RGBA` to simplify the type definitions, and make it easier to change color types in the future
A concrete advantage is that a geometry is now only definitively colored after a call to `colorize` and this can be checked by typescript automatically. So for example this gives a type warning:
```ts
function example(geom: Geom3) {
console.log(geom.color[0])
}
```
But this considered valid (correctly):
```ts
function …
```
> refactor(modeling): refactor geometry types

- packages/modeling/src/geometries/poly3/measureBoundingSphere.d.ts
- packages/modeling/src/geometries/poly3/measureBoundingSphere.js
- packages/modeling/src/geometries/poly3/measureBoundingSphere.test.js
- packages/modeling/src/operations/booleans/trees/PolygonTreeNode.js
A number of performance issues were pointed out by @briansturgill. One of them was caching of `measureBoundingSphere` in the BSP boolean operations (#1094). BSP operations use measureBoundingSphere to determine if objects overlap.
By adding caching to `poly3.measureBoundingSphere`, we can get a significant speed up in BSP operations. This uses the same caching code as in the `measurements` package, but applied to the `poly3` package.
For unioning two overlapping spheres with 100 segments, we get **49,366** cache misses (measurements), and **97,030,301** cache hits saved! That's a 99.95% cache hit rate. :grimacing: 
This results in major performance improvements as measured in BSP union operations. Comparing the last release 2.5.10, master (with no-hypot #1099), and measureBoundingSphere …
> perf(modeling): cache poly3.measureBoundingSphere for BSP performance

- packages/web/src/ui/flow/design.js
- packages/web/src/ui/flow/reducers.js
This PR splits `web/src/ui/flow/design.js` into two files. The original `design.js` is very long, 647 lines. This makes it hard to comprehend how the web UI works. The goal here is to make it easier to maintain the web UI code.
This PR pulls out the `reducers` into their own file `reducers.js`. This splits the original file neatly in two:
- 353 lines for `design.js`
- 305 lines for the new `reducers.js`
Tested locally, seems to work fine.
> refactor(web): split out reducers from web flow

- .gitignore
- packages/io/svg-deserializer/src/shapesMapGeometry.js
- packages/io/svg-deserializer/tests/issue.1135.test.js
fix for #1135
there is no need to throw error when last point is same as first point in svg.
> fix 1135 svg start == end point throw unecessary error

- README.md
- lerna.json
- package.json
- packages/cli/README.md
- packages/core/README.md
- packages/examples/README.md
- packages/io/amf-deserializer/README.md
- packages/io/amf-serializer/README.md
- packages/io/dxf-deserializer/README.md
- packages/io/dxf-serializer/README.md
- packages/io/io-utils/README.md
- packages/io/io/README.md
- packages/io/json-deserializer/README.md
- packages/io/json-serializer/README.md
- packages/io/obj-deserializer/README.md
- packages/io/obj-serializer/README.md
- packages/io/stl-deserializer/README.md
- packages/io/stl-serializer/README.md
- packages/io/svg-deserializer/README.md
- packages/io/svg-serializer/README.md
- packages/io/x3d-deserializer/README.md
- packages/io/x3d-serializer/README.md
- packages/modeling/README.md
- packages/utils/array-utils/README.md
- packages/utils/regl-renderer/README.md
- packages/vtree/README.md
- packages/web/README.md
- pnpm-lock.yaml
Building upon the last change, moving to PNPM package management, these changes move the publishing to lerna-lite. The changes also include some changes to use the PNPM workspaces correctly.
All scripts were tested, except final publishing which should be part of a 'v3-prerelease'.
FYI. NO CODE CHANGES.
> build(all): moving to lerna-lite for publishing

- packages/modeling/src/operations/extrusions/extrudeHelical.d.ts
- packages/modeling/src/operations/extrusions/extrudeHelical.js
- packages/modeling/src/operations/extrusions/extrudeHelical.test.js
- packages/modeling/src/operations/extrusions/index.js
Adds the `extrudeHelical` functionality as discussed in #1162
This supposes that the `geom2` that is to be extruded is laying fully in the positive x plane. Otherwise you get issues with inside-out polygons, as discussed in #1012
It allows for the generating of a helix, tapered helix (`endRadiusOffset !== 0`) and spiral (`pitch === 0, endRadiusOffset !== 0`)
Simple example:
```js
const jscad = require("@jscad/modeling")
const { circle } = jscad.primitives
const { extrudeHelical } = jscad.extrusions
const main = () => {
return extrudeHelical(
{
angle: Math.PI * 4,
pitch: 10,
endRadiusOffset: -5,
segments: 64
},
circle({ size: 3, center: [10, 0] })
)
}
module.exports = { main }
```
Resulting in a tapered helix:
I will need some extra guidance with adding the documentation, as I could not …
> add extrudeHelical

- packages/web/css/demo.css
- packages/web/src/ui/views/editor.js
Fixes #1174, by adding a subtle message in the editor on how to render the code.
Currently looks like this:
> add render hotkey message in editor

- packages/io/stl-deserializer/README.md
The instructions in the README no longer work with the current codebase, as they don't match the `deserialize()` function signature.
> Update Usage instructions for stl-deserializer

- packages/cli/cli.js
- packages/cli/src/env.js
- packages/cli/src/parseArgs.js
I noticed that the CLI prints out the wrong usage help information. To see, just do `npm i -g @jscad/cli` and then run `jscad`. Note that the executable is called `jscad` not `openjscad`.
> fix(cli): corrected CLI usage message

- packages/core/package.json
The core package has a dependency on `json5`. There is a recent CVE vulnerability on version < 2.2.2. I was alerted by dependabot.
[CVE-2022-46175](https://nvd.nist.gov/vuln/detail/CVE-2022-46175)
This PR updates to `json5` version 2.2.3 which is not vulnerable to the parsing vulnerability.
> fix(core): update json5 dependency

- packages/modeling/src/geometries/geom2/validate.js
- packages/modeling/src/geometries/geom2/validate.test.js
- packages/modeling/src/maths/utils/intersect.js
- packages/modeling/src/operations/expansions/offsetGeom2.test.js
Adds a geom2 validation check for self-intersecting polygons. This is a helpful check as I continue to improve the 2D operations.
I added validate.test.js with validation tests for geom2 as well.
I had to add an extra parameter to maths/utils/intersect.js. This actually makes it consistent with the intersect routine in martinez/segment_intersection.js. Hopefully they can be merged one day, but not yet.
> test(modeling): V3 check for self-intersecting geom2

- packages/modeling/src/geometries/poly2/arePointsInside.js
- packages/modeling/src/geometries/poly2/clone.test.js
- packages/modeling/src/geometries/poly2/create.d.ts
- packages/modeling/src/geometries/poly2/create.js
- packages/modeling/src/geometries/poly2/create.test.js
- packages/modeling/src/geometries/poly2/index.js
- packages/modeling/src/geometries/poly2/isA.js
- packages/modeling/src/geometries/poly2/isA.test.js
- packages/modeling/src/geometries/poly2/isConvex.js
- packages/modeling/src/geometries/poly2/isSimple.js
- packages/modeling/src/geometries/poly2/measureArea.js
- packages/modeling/src/geometries/poly2/measureBoundingBox.js
- packages/modeling/src/geometries/poly2/reverse.js
- packages/modeling/src/geometries/poly2/reverse.test.js
- packages/modeling/src/geometries/poly2/toPoints.js
- packages/modeling/src/geometries/poly2/toPoints.test.js
- packages/modeling/src/geometries/poly2/toString.js
- packages/modeling/src/geometries/poly2/transform.js
- packages/modeling/src/geometries/poly2/transform.test.js
- packages/modeling/src/geometries/poly2/type.d.ts
- packages/modeling/src/geometries/poly2/validate.js
- packages/modeling/src/geometries/poly2/validate.test.js
- packages/modeling/src/operations/extrusions/earcut/assignHoles.js
This PR changes `poly2.vertices` to `poly2.points`.
The problems is that otherwise there is no difference between the structure of poly2 and poly3. So you would have the following weirdness:
```js
poly2.isA( poly3.create() ) == true
poly3.isA( poly2.create() ) == true
```
By using `points` instead of `vertices` we can tell the difference between a poly2 and a poly3.
More generally, I like the idea of using "points" to refer to 2D points, and "vertices" to refer to 3D points. I think it could help make JSCAD code easier to understand if we are consistent about that.
I also added tests for `poly2.reverse` and `poly2.toPoints` since I noticed that they were not covered by existing tests.
> refactor(modeling)!: V3 convert poly2 vertices to points

- packages/modeling/src/operations/booleans/intersectGeom2.test.js
- packages/modeling/src/operations/booleans/intersectGeom3.test.js
- packages/modeling/src/operations/booleans/subtractGeom2.test.js
- packages/modeling/src/operations/booleans/subtractGeom3.test.js
- packages/modeling/src/operations/booleans/unionGeom2.test.js
- packages/modeling/src/operations/booleans/unionGeom3.test.js
- packages/modeling/src/operations/expansions/offsetGeom2.test.js
- packages/modeling/src/operations/extrusions/extrudeFromSlices.test.js
- packages/modeling/src/operations/extrusions/extrudeLinear.test.js
- packages/modeling/src/operations/extrusions/extrudeRectangular.test.js
- packages/modeling/src/operations/extrusions/extrudeRotate.test.js
- packages/modeling/src/operations/extrusions/project.test.js
- packages/modeling/src/operations/transforms/center.test.js
- packages/modeling/src/operations/transforms/mirror.test.js
- packages/modeling/src/operations/transforms/rotate.test.js
- packages/modeling/src/operations/transforms/scale.test.js
- packages/modeling/src/operations/transforms/translate.test.js
Suppose you're a developer for JSCAD. And you are making changes to the modeling library, and they are good changes. But as a result of changes, the order of points change, without actually changing the shape of the geometry. But the JSCAD test suite makes assumptions about point order. So you have to then update a bunch of tests with new point data to match.
This is all fine. But wouldn't it be nice to test against properties of the geometries that do not depend on point order? So you can be more confident that we aren't breaking the geometries. If you see points change, it's not necessarily a problem. If the volume changes, something is definitely wrong.
So this PR adds `measureArea` and `measureVolume` assertions to the existing tests on all operations. [V3]
> test(modeling): tests for area and volume of operations

- packages/modeling/src/geometries/geom2/create.js
- packages/modeling/src/geometries/geom2/index.js
- packages/modeling/src/geometries/geom2/toString.test.js
- packages/modeling/src/geometries/geom3/toString.test.js
- packages/modeling/src/geometries/poly2/isConvex.test.js
- packages/modeling/src/geometries/poly2/toString.js
- packages/modeling/src/geometries/poly2/toString.test.js
- packages/modeling/src/geometries/poly2/validate.test.js
- packages/modeling/src/geometries/poly3/toString.js
- packages/modeling/src/geometries/poly3/toString.test.js
- packages/modeling/src/geometries/slice/earcut/polygonHierarchy.js
- packages/modeling/src/geometries/slice/toString.js
- packages/modeling/src/geometries/slice/toString.test.js
- packages/modeling/src/maths/utils/intersect.d.ts
- packages/modeling/src/maths/utils/intersect.test.js
Misc fixes and testing enhancements for V3. Includes:
- Fix `maths.utils.intersect` type defintion. Thanks @youssefsharief
- Add tests for `maths.utils.intersect`
- Fix `slice.toString`
- Add tests for `*.toString` to all geometries
- Make `toString` more similar across geometries
- Minor comment fixes
> fix(modeling): V3 small fixes

- packages/cli/cli.conversions.test.js
- packages/cli/cli.js
- packages/cli/cli.parameters.test.js
- packages/cli/package.json
- packages/cli/src/determineOutputNameAndFormat.js
- packages/cli/src/env.js
- packages/cli/src/generateOutputData.js
- packages/cli/src/parseArgs.js
- packages/core/src/code-evaluation/rebuildGeometryCli.js
- packages/core/src/web/walkFileTree.js
- packages/io/io/src/formats.js
- pnpm-lock.yaml
These changes do a few things:
- fixed a few of the io package functions
- fixed core package imports of io package functions
- reworked CLI logic to use the new io package exports and functions
- converted CLI tests to use import
- HACK of core to use dynamic import
What was learned...
- dynamic import() is the only way to dynamically load designs with import / export
- dynamic import() is asynchronous, therefore calling functions must be async as well... as well as...
What's missing...
- no idea if dynamic import() works in all browsers
- no idea if dynamic import() works in web workers
- no idea if dynamic import() can import whole projects
- no idea if designs with require / module and import / export can be supported
> feat(cli): reworked logic to use new io package exports and functions

- .github/workflows/node.yml
- packages/modeling/src/curves/bezier/arcLengthToT.d.ts
Fix the type definitions in `arcLengthToT.d.ts` to make the first argument required.
Also add `tsd:test` to CI.
Fixes #1223
> fix(modeling): arcLengthToT first argument is required

- packages/io/svg-deserializer/src/helpers.js
- packages/io/svg-deserializer/src/shapesMapGeometry.js
- packages/io/svg-deserializer/src/shapesMapJscad.js
- packages/io/svg-deserializer/tests/instantiate.test.js
Fix a bunch of bugs in the svg-deserializer. Specifically we were not computing quadratic bezier paths correctly.
To convert a quadratic bezier curve to a cubic curve requires generating the following control points:
```
C0 = Q0
C1 = Q0 + (2/3) (Q1 - Q0)
C2 = Q2 + (2/3) (Q1 - Q2)
C3 = Q2
```
But the code was previously doing:
```
C0 = Q0
C1 = Q1
C2 = Q1
C3 = Q2
```
Visually this means we were using the green dot twice, instead of computing the red dots:
Fixes #1222
Also found a bug where we were not converting svg unit for `[cx, cy]` on the svg `t` command. 
Cleaned up the code style to make more readable. Changes to functionality were only in `q`, `Q`, `t`, and `T` svg commands.
> fix(svg-deserializer): fix quadratic bezier paths

- packages/io/x3d-serializer/src/index.js
- packages/io/x3d-serializer/tests/geom3ToX3D.test.js
fixes #1231
some additional cleanup as suggested by standardx.
> X3D serializer: Material RGB colors

- packages/modeling/src/primitives/circle.js
- packages/modeling/src/primitives/circle.test.js
- packages/modeling/src/primitives/cube.js
- packages/modeling/src/primitives/cube.test.js
- packages/modeling/src/primitives/cuboid.js
- packages/modeling/src/primitives/cuboid.test.js
- packages/modeling/src/primitives/cylinder.js
- packages/modeling/src/primitives/cylinder.test.js
- packages/modeling/src/primitives/ellipse.js
- packages/modeling/src/primitives/ellipse.test.js
- packages/modeling/src/primitives/ellipsoid.js
- packages/modeling/src/primitives/ellipsoid.test.js
- packages/modeling/src/primitives/geodesicSphere.js
- packages/modeling/src/primitives/geodesicSphere.test.js
- packages/modeling/src/primitives/rectangle.js
- packages/modeling/src/primitives/rectangle.test.js
- packages/modeling/src/primitives/roundedCuboid.js
- packages/modeling/src/primitives/roundedCuboid.test.js
- packages/modeling/src/primitives/roundedCylinder.js
- packages/modeling/src/primitives/roundedCylinder.test.js
- packages/modeling/src/primitives/roundedRectangle.js
- packages/modeling/src/primitives/roundedRectangle.test.js
- packages/modeling/src/primitives/sphere.js
- packages/modeling/src/primitives/sphere.test.js
- packages/modeling/src/primitives/square.js
- packages/modeling/src/primitives/square.test.js
This PR allows primitives to "scale to zero" in size. Specifically, for rectangles and cuboids allow size equal to zero. And for ellipses and cylinders allow radius equal to zero.
Previously these primitives would throw an exception if the size was zero. This leads to a bad user experience in cases where you have a parametric design that has a parameter that might scale to zero and disappear. Right now, you need awkward special cases in your code to handle that (a user raised this issue on discord recently).
Another example where this is helpful: Using a slider parameter, today if you slide it to zero you get an exception and the design does not update on the screen. After this PR, you can scale these to zero, and it works fine:
```js
const { circle, cube, cylinder, square } = …
```
> feat(modeling): allow zero size in primitives

- packages/modeling/src/operations/modifiers/retessellate.js
Based on this discussion https://github.com/jscad/OpenJSCAD.org/discussions/1247 I have refactored `retessellate.js` to improve performance.
This function is used by all boolean operations and is the main reason why sometimes they're really slow.
To measure the performance I used a geometry with ~15k polygons which gets reduced to ~7.5k polygons.
Results for current implementation of `retessellate.js` :
- total execution time ~580ms of which:
-  ~465ms used to determine coplanar polygons (lines 29-39) 
- ~115ms used to call `reTesselateCoplanarPolygons`
Results for new implementation:
- total execution time ~120ms of which 
- ~18ms used to determine coplanar polygons (lines 21-22) 
- ~102ms used to call `reTesselateCoplanarPolygons`
There is an ~5x overall performance improvement, but if …
> Performance improvements for retessellate

- packages/cli/README.md
- packages/cli/cli.js
- packages/cli/cli.parameters.test.js
- packages/cli/package.json
- packages/cli/src/generateOutputData.js
- packages/cli/src/parseArgs.js
Adds the CLI export utilities a `-p` flag to output multiple parts as separate files as well as a `-z` flag to zip the multiple files into one `design.zip` exported file
related: https://github.com/jscad/OpenJSCAD.org/issues/1262 
* [ x] Have you followed the guidelines in our Contributing document?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ x] Does your submission pass tests?
> cli option to output files as individual part files or .zip of parts

- packages/cli/cli.js
- packages/cli/cli.parameters.test.js
- packages/cli/src/env.js
- packages/cli/src/generateOutputData.js
- packages/cli/src/parseArgs.js
- packages/modeling/src/measurements/measureBoundingSphere.d.ts
- packages/modeling/src/measurements/measureCenter.d.ts
- packages/modeling/src/measurements/measureCenterOfMass.d.ts
- packages/modeling/src/measurements/measureDimensions.d.ts
- packages/modeling/src/measurements/types.d.ts
Corrections to the CLI to generate blobs correctly as singular or multiple parts. The generate parts option now works properly.
NOTE: There are also some changes to the Typescript definitions in order to get the CI running again.
> fix(cli): rework logic for generating blobs, both singular and multiple as parts

- packages/modeling/src/geometries/geom2/reverse.js
- packages/modeling/src/geometries/geom2/reverse.test.js
- packages/modeling/src/operations/extrusions/extrudeLinear.test.js
- packages/modeling/src/operations/extrusions/extrudeLinearGeom2.js
- packages/modeling/src/operations/extrusions/extrudeLinearPath2.js
- packages/modeling/src/operations/extrusions/extrudeRotate.js
- packages/modeling/src/operations/extrusions/extrudeRotate.test.js
- packages/modeling/src/operations/extrusions/project.js
- packages/modeling/src/operations/extrusions/project.test.js
- packages/modeling/src/operations/hulls/hull.test.js
- packages/modeling/src/operations/hulls/hullChain.js
- packages/modeling/src/operations/hulls/hullChain.test.js
- packages/modeling/src/operations/offsets/offsetFromPoints.js
- packages/modeling/src/operations/offsets/offsetFromPoints.test.js
- packages/modeling/src/operations/offsets/offsetGeom2.js
- packages/modeling/src/operations/offsets/offsetGeom2.test.js
- packages/modeling/src/operations/offsets/offsetGeom3.js
- packages/modeling/src/operations/offsets/offsetGeom3.test.js
- packages/modeling/src/operations/offsets/offsetPath2.js
- packages/modeling/src/operations/offsets/offsetPath2.test.js
- packages/modeling/src/operations/offsets/offsetShell.js
This PR preserves the color attribute when applying operations like `offset` and `extrude` and `project`.
This seems like a clear improvement for users of JSCAD. If you have a 2D object with color like on the left, would you expect extrusion to preserve the color? Or lose it?
<details>
<summary>preserve-color.js</summary>
```js
import * as jscad from '@jscad/modeling'
const { colorize } = jscad.colors
const { extrudeLinear } = jscad.extrusions
const { square } = jscad.primitives
const { translate } = jscad.transforms
export const main = () => {
const obj2d = [
colorize([1, 0, 0], square({ center: [0, -4] })),
colorize([0, 1, 0], square({ center: [0, 0] })),
colorize([0, 0, 1], square({ center: [0, 4] })),
]
return [
translate([-4, 0], obj2d),
translate([4, 0, 0], extrudeLinear({}, …
```
> feat(modeling): preserve color for offset and extrude 

- .github/workflows/node.yml
- package.json
- packages/modeling/src/geometries/poly2/arePointsInside.js
- packages/modeling/src/geometries/poly3/type.d.ts
- packages/modeling/src/maths/mat4/invert.js
- packages/modeling/src/maths/mat4/isIdentity.js
- packages/modeling/src/maths/mat4/isOnlyTransformScale.js
- packages/modeling/src/measurements/measureEpsilon.js
- packages/modeling/src/operations/offsets/index.d.ts
- packages/modeling/src/operations/offsets/offset.d.ts
- packages/modeling/src/operations/offsets/offset.js
- packages/modeling/src/operations/offsets/offsetFromPoints.d.ts
- packages/modeling/src/operations/offsets/offsetFromPoints.js
- packages/modeling/src/operations/offsets/offsetGeom2.js
- packages/modeling/src/operations/offsets/offsetShell.js
- pnpm-lock.yaml
This PR fixes the failing `tsd` test.
In order to make the tests pass with our new ES module style imports I had to make the following changes:
- Update `tsd` npm dependency
- A couple minor type issues that surfaced
- In three files I had to add `@typedef` for `Mat4`. I'm not sure why this was needed, but it did fix the issue.
- Added `V3` branch to the list of branches to run CI on
As part of updating the `tsd` dependency, it updated the lockfile version and caused a bunch of diff noise. I'm assuming it's because on my machine I used the latest node/npm/pnpm version.
> fix(modeling): fix tsd tests

- jsdoc.json
- lerna.json
- package.json
- packages/io/amf-deserializer/package.json
- packages/io/amf-serializer/package.json
- packages/io/test/package.json
- packages/modeling/src/maths/mat4/invert.d.ts
- packages/modeling/src/maths/mat4/invert.js
- packages/modeling/src/maths/mat4/isIdentity.d.ts
- packages/modeling/src/maths/mat4/isIdentity.js
- packages/modeling/src/maths/mat4/isOnlyTransformScale.d.ts
- packages/modeling/src/maths/mat4/isOnlyTransformScale.js
These changes are in preparation for publishing V3 alpha versions of the packages.
There are some code changes to modeling, as JSDOC barfed on those '@typedef' docs strings in mat4. I added proper TS definitions for those functions, and all is good again.
> V3 prerelease part 3

- lerna.json
- package.json
- packages/core/package.json
- packages/web/package.json
- pnpm-lock.yaml
These are changes in preparation for publishing V3 packages. The changes include:
- bumped lerna-lite to version 2.5.1
- added vtree to list of packages in order to sync workspace with lerna
- remove version script from core/web packages as these will not be published
> V3 prerelease preparations

- packages/modeling/src/operations/booleans/intersect.js
- packages/modeling/src/operations/booleans/intersect.test.js
- packages/modeling/src/operations/booleans/scission.js
- packages/modeling/src/operations/booleans/subtract.js
- packages/modeling/src/operations/booleans/subtract.test.js
- packages/modeling/src/operations/booleans/union.js
- packages/modeling/src/operations/booleans/union.test.js
A user on discord had a question, and I realized that his design revealed a weird behavior in `union` when invalid geometries are given. Simplified user code:
```js
return union(vectorText({ input: 'I' }), vectorText({ input: ' ' }))
```
Rather than throwing an error in `union`, this actually returns the value `4`. Weird.
It makes sense when you look at the code. `vectorText` returns an array of points like:
```js
vectorText({ input: 'I' }) => [[[4, 21], [4, 0]]]
```
Which gets flattened by union, and then union doesn't know how to deal with non-geometries so it just returns the first element from the flattened list which is the number `4`. Very weird.
I don't like throwing errors if we can avoid it. But in this case, it feels like the right thing to do is to tell the user "hey this is …
> fix(modeling): boolean argument checks

- packages/modeling/src/geometries/geom2/transform.js
- packages/modeling/src/geometries/geom2/transform.test.js
- packages/modeling/src/operations/extrusions/extrudeRotate.js
- packages/modeling/src/operations/transforms/mirror.test.js
Fixes #1301 (thanks @gilboonet)
When a mirroring transform is applied to a geometry, we should reverse the point order so that orientation is preserved.
This was already done for geom3/poly3 geometries [here](https://github.com/jscad/OpenJSCAD.org/blob/master/packages/modeling/src/geometries/poly3/transform.js#L15-L18), but was not applied to geom2.
This PR uses the 2D determinant in `geom2.transform` to check if a transform is a mirroring transform in 2D.
Added to V3 branch since this is technically a breaking change. Although I would argue this is a fix of bad behavior.
> fix(modeling): geom2 mirroring transform

- packages/modeling/src/primitives/polygon.d.ts
- packages/modeling/src/primitives/polygon.js
- packages/modeling/src/primitives/polygon.test.js
These changes add a new option to the polygon primitive; orientation. If set to 'clockwise' then the geometry is reversed.
These changes address #1012
> fix(modeling): added orientation option to polygon

- packages/utils/array-utils/package.json
- packages/utils/array-utils/src/index.d.ts
- packages/utils/array-utils/src/index.test-d.ts
- packages/utils/array-utils/src/recursiveArray.d.ts
- packages/utils/array-utils/src/toArray.d.ts
These changes correct the typescript definitions for the function in array-utils. The test:tsd script has been added to test the definitions going forward.
> fix(array-utils): corrected typescript definitions

- packages/modeling/src/primitives/roundedCuboid.js
- packages/modeling/src/primitives/roundedCylinder.js
- packages/modeling/src/primitives/roundedRectangle.js
Got the error yesterday and spotted the typo
> fix(typo): fix then/than in rounded error messages

- packages/io/x3d-deserializer/src/parse.js
If we use this parser for multiple files with identical DEF signatures this caching will remove necessary definitions for the x3d.
Now it will be empty for every new parser.
> fix: x3d defs caching

- packages/modeling/src/index.js
This PR adds a "V2 compatibility shim" to V3.
In PR #1294 we flattened the JSCAD package heirarchy so that functions like `union` and `extrudeLinear` are now in the top level package object:
```diff
-import { booleans } from '@jscad/modeling'
-const { union } = boolean
+import { union } from '@jscad/modeling'
```
But what about all the hundreds of designs out there for V2? They will all break, annoyingly, in the migration to V3.
This PR keeps the flattened structure for V3 but ALSO exports a similar structure to V2. This is not 100% api compatible, due to some fundamental changes in V3, but it is pretty close, and I tried a couple of my designs from V2 against this, and they actually all just-worked!
Feedback welcome, but I think this would make the transition from V2 to V3 much smoother …
> feat(modeling): V2 api compatibility shim
