jscad/OpenJSCAD.org

- openscad.js
Previous was a copy-paste of rotate that didn't really work
Fixes #65
> Fix mirror implementation

- htaccess_example
- index.html
- remote.php
Also does something different... I've added a php remote script (to fetch) and a .htaccess rewrite rule so it can also be installed on a php enable server.
> Issue#47 also accept parameters on url

- openjscad.js
This is another set of changes to improve the state management of both Processor and Viewer objects. The performance of the viewer improves as redundant changes to the GL canvas are eliminated, i.e. less initialization.
Summary:
- "state" attributes have been added
- old attributes have been removed; processing and hasValidCurrentObject
- logic has been improved to set and check states according
- access methods to "state" have been added
There are a few more JavaScript syntax changes as well. I missed those last time.
> Rewrite of state manage for performance and stability

- index.html
- openjscad
- openjscad.js
- openscad.js
Changes include:
- Added OpenJsCad.version and changed code to use this version
- Changed the comment that is shown while rendering "Rendering code" to "Rendering"
- Removed tabs and indented properly
If you run 'diff --ignore-all-space' with old and new versions then you find that there are just a few minor changes.
> Preparations for More Changes

- CONTRIBUTING.md
- examples/balloons.jscad
- examples/benchmark.jscad
- examples/benchmark_cag.jscad
- examples/benchmark_csg.jscad
- index.html
- openscad.js
There were some changes required to benchmark.jscad as that example was still using 'me'. I also changed the calculations in order to calculate iterations per second.
A new example of the new parameter types was added as well, examples/balloons.jscad
And some new color functions were added to openscad.js to assist in the conversion of HTML5 colors to and from RGB colors.
Testing is also complete, both performance and general. Please review the Alpha 0.3.1 pages.
> Changes for Alpha Release 0.3.1

- js/ui-drag-drop.js
- openjscad.js
This corrects drap and drop for single files of any accepted type, as well as combinations of types.
> Fix for Drap Drop

- index.html
As requested for Alpha Release 0.3.2
> Disabled options

- examples/cnc-cutout.jscad
- js/index.js
- openjscad.js
This corrects currentObject inside the Processor, which then allows the downloadable formats to be determined properly.
> Corrected retention of objs as currentObject

- openjscad.js
This fixes issue #130 as mentioned in the OpenJSCAD.org community.
> Remove remote links and parameters before setting baseurl

- README.md
- openjscad.js
As agreed, I'm only changing the dates for this fix.
> Changed the date of the release as as result of a quick fix

- openjscad.js
> Corrected date in OpenJsCad.version

- Makefile
- README.md
- index.html
- js/jscad-parseSVG.js
- js/ui-drag-drop.js
- js/ui-editor.js
- min.html
- openjscad.js
- openscad.js
Testing has been completed. Please see the 0.5.0 WIKI pages.
These are the final changes for the version numbers, comments, and a small bug fix.
> Last Changes for 0.5.0

- Makefile
- README.md
- index.html
- js/index.js
- js/jscad-parseAMF.js
- js/ui-drag-drop.js
- js/ui-editor.js
- js/worker-conversion.js
- min.html
- openjscad
- openjscad.js
- openscad.js
Version number changes and comments
> Preparations for Alpha Release 0.5.1

- formats.js
Corrected toAMFString() to provide colors only when set, i.e. no defaults
Added CSG.toJSON() and CAG.toJSON() functions
Added CSG.fromJSON() and CAG.fromJSON() functions
> Merging changes from CSG library

- big.css
- big.html
- openjscad.js
- style.css
This enhancement allows both Processor and Viewer options on construction. This is required for designs that want to adjust the grid, camera, etc.
Included is a new example showing how to set the options. big.html
> Enhanced Processor constructor to accept Viewer options

- examples/axis-coupler.jscad
- examples/logo_big.jscad
- index.html
- openjscad.css
- openjscad.js
This enhancement adds two range selectors to the top right corner. If the script returns an array of objects the these selectors are show, and allow the user to adjust the view to include a subset of the objects. For multi-part designs, this allows the users to select the part(s) for viewing, and download.
Let me know what you think.
> Enhanced to allow a selection from the returned objects

- Makefile
- README.md
- big.html
- index.html
- min.html
- openjscad
- openjscad.js
- openscad.js
Changes to move versions to 0.5.2
And release notes
> Alpha Release 0.5.2 Preparations

- js/index.js
- js/jscad-parseSVG.js
Fixed an issue with scaling viewports of SVG images
Fixed an issue with loading of remote URLS, which was caused by the new local caching
> Small Fixes

- openjscad.js
As requested, these changes make the format selection and the conversion logic more pragmatic. All for the better, I think.
> Enhanced Format Selection and Conversion

- src/io/convertToBlob.js
- src/io/createConversionWorker.js
- src/io/writers/CAGToDxf.js
- src/io/writers/CAGToSvg.js
- src/io/writers/CSGToAMF.js
- src/io/writers/CSGToStla.js
- src/io/writers/CSGToStlb.js
- src/io/writers/CSGToX3D.js
- src/jscad/rebuildSolid.js
Various fixes:
- lower/uppercase issues with some imports
> Various fixes

- package.json
- removes bad build command
- updated dependency paths/urls
> Package fixes

- Makefile
Also fixes paths for files in root directory, not js subdir.
> chore(build): fix Issue #227: hardcoded bin path, sudo

- dist/index.js
- dist/opt.js
- package.json
This fixes the current issues with the dependencies.
> Dependency fixes

- src/ui/editor.js
- src/ui/viewer/jscad-viewer-lightgl.js
Please review these fixes.
These correct functionality for:
- Resizing the view canvas when the window size changes
- Resting the viewer camera upon hitting the HOT key
> Fixes to Correct Lost Functionality

- package.json
- src/ui/viewer/controls.js
- src/ui/viewer/jscad-viewer-helpers.js
- src/ui/viewer/jscad-viewer-lightgl.js
- src/ui/viewer/jscad-viewer.js
- src/ui/viewer/lightgl.js
- style.css
READY TO merge :)
This PR adds a few fixes and tweaks for the mobile & desktop '3d' controls, and simplifies handling considerably as far as camera controls go.
> mobile & control fixes

- CONTRIBUTING.md
- Makefile
- README.md
- index.html
- package.json
- viewer-minimal.html
- viewer-options.html
- [] Update README
- [] reorganize to make easy readying
- [] add 0.6.0 changes to history
README
- How about adding Issues for the remaining TODOs? And removing this section?
- How about moving History to the end? Or a separate file? We need a better method.
CONTRIBUTE
- Looks complete. Anything missing? Anything wrong?
src/NOTES
- Required?
> Changes for 0.6.0 release

- src/cli.js
This fixes lack of ability to run the new CLI.
> fix(cli): fixed lacking shebang

- src/io/prepareOutput.js
- src/jscad/processor.js
Fixes/tweaks of various things:
> various fixes and tweaks for release

- src/ui/viewer/jscad-viewer-lightgl.js
solves annoying issues with camera rotation when editing code mentioned in #281
> fix(controls): changed camera controls to only work in 3d view

- README.md
This PR adds a "know issues" section to the README to avoid user frustration & duplicate issues
> Known issues

- .travis.yml
- README.md
- package-lock.json
- package.json
- src/cli/cli.test.js
- src/core/convertToSolid.js
- src/core/jscad-worker.js
- src/core/utils.js
This PR is very important !!
- It solves various issues fixes in the other repositories of jscad
- It fixes the messy depencies of jscad/io
- it updates some of the automation
- it fixes the breaking tests because of the changes in @jscad/io
> chore(): fixes and depency updates

- src/ui/dragDrop/walkFileTree.js
updated walkFileTree to stop using the deprecated readAsBinaryString function
> refactor(walkfileTree): updated api uses

- src/cli/cli.js
- src/cli/cli.test.js
- src/cli/generateOutputData.js
- src/io/formats.js
WORK IN PROGRESS DO NOT MERGE 
This PR 
> fix(cli): fixes for multiple cli issues

- package-lock.json
- package.json
This PR pulls in the latest version of scad-api and its upgrades and fixes to `rotate_extrude` & `torus`
fixes #320
> fix(pkg): update scad-api version for rotate_extrude fixes and updates

- examples/gear.jscad
> show min,max,step in gears example

- examples/transformations.jscad
- package-lock.json
- package.json
- src/ui/examples.js
* added example
* updated examples listing
> feat(transforms): added updated scad-api with matrix transforms support

- src/cli/cli.test.js
- src/cli/generateOutputData.js
- src/cli/getParameterValues.js
- src/core/getParamValues.js
This PR fixes #341 , adds casting/conversion of raw CLI params into those specified in parameterDefintions, and adds tests to ensure no regression.
> fix(CLI): added system to convert CLI params to the correct type

- packages/cli/README.md
Just a small typo fix in the CLI README
> docs(cli): fixed wrong logo url

- CONTRIBUTING.md
- README.md
- packages/cli/README.md
- packages/core/README.md
- packages/examples/README.md
- packages/web/README.md
- packages/web/index.html
- packages/web/src/ui/index.js
Updates to md files as well as html and js files, correcting links to user guides and user groups.
Fixes #366
> Fix document links

- packages/cli/package.json
- packages/core/package.json
- packages/web/package.json
This PR fixes some issues with the dxf-serializer
> fix(dxf-serializer): updated @jscad/io dependency for dxf-serializer fixes

- package.json
- packages/desktop/package.json
- packages/desktop/src/sideEffects/appUpdates.js
- packages/desktop/src/ui/reducers.js
- packages/desktop/src/ui/views/status.js
This PR updates/fixes the in-app notifications system since a few things changed with the move into this repository/monorepo.
> fix(desktop): fix desktop update notifications

- packages/desktop/package.json
Emergency fix for an accidental reversion of the desktop packages's version
> fix(pkg): fixed reverted pkg version

- docs/index.md
> fixing minor markdown typo

- CODE_OF_CONDUCT.md
> Initial version of code of conduct

- packages/cli/package.json
- packages/core/package.json
- packages/desktop/package.json
- packages/web/package.json
Adds latest dependencies where applicable.
> chore(pkg): updated dependencies (latest of @jscad/csg & @jscad/io)

- README.md
> docs(README): added disclaimer about V1 vs V2

- README.md
I'm assuming that you'd rather direct people to something like this: 
than this: 
* [✅] Have you followed the guidelines in our Contributing document?
* [✅ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
> update packages link to a non-github raw file

- .travis.yml
- lerna.json
- package.json
> chore(lerna): Lerna update

- CONTRIBUTING.md
- README.md
- packages/cli/README.md
- packages/core/README.md
- packages/examples/README.md
- packages/io/CONTRIBUTING.md
- packages/io/README.md
- packages/io/amf-deserializer/README.md
- packages/io/amf-serializer/README.md
- packages/io/dxf-deserializer/README.md
- packages/io/dxf-serializer/README.md
- packages/io/gcode-deserializer/README.md
- packages/io/io-utils/README.md
- packages/io/io/README.md
- packages/io/json-deserializer/README.md
- packages/io/json-serializer/README.md
- packages/io/obj-deserializer/README.md
- packages/io/scad-deserializer/README.md
- packages/io/stl-deserializer/README.md
- packages/io/stl-serializer/README.md
- packages/io/svg-deserializer/README.md
- packages/io/svg-serializer/README.md
- packages/io/x3d-serializer/README.md
- packages/web/README.md
- packages/web/dist/jscad-full.min.js
- packages/web/index-old.html
- packages/web/src/ui/views/help.js
This PR updates all our community links.
Very important: we need a redirect on our new site to the new forums before merging this.
> chore(docs): Update community links 

- packages/core/code-loading/loadDesign.js
- packages/core/code-loading/transformSources.js
This fixes issues when converting external formats (STL, DXF, etc) to JSCAD scripts.
> Fix (CORE) transforming of external formats to scripts

- packages/utils/regl-renderer/src/geometry-utils/cagToGeometries.js
- packages/utils/regl-renderer/src/geometry-utils/entitiesFromSolids.js
- packages/utils/regl-renderer/src/rendering/commands/drawMesh/index.js
- packages/web/src/sideEffects/localStorage/index.js
- packages/web/src/sideEffects/state/index.js
- packages/web/src/ui/flow/design.js
- packages/web/src/ui/views/viewer.js
Small sets of fixes for blocker bugs before further changes :)
> fix(V2): small tweaks and fixes for V2

- packages/io/amf-deserializer/index.js
- packages/io/amf-deserializer/translate.js
UG.. Missed this one!
These changes correct translate() to provide V2 require and export statements.
> V2 : Fix AMF Deserializer

- packages/io/dxf-deserializer/index.js
- packages/io/dxf-deserializer/tests/test-2d-translation.js
- packages/io/dxf-deserializer/tests/test-3d-translation.js
- packages/io/dxf-deserializer/translate.js
Yup... another.
These changes add the V2 require and export statements to the translated script.
> V2 : Fix DXF Deserializer

- packages/io/obj-deserializer/index.js
- packages/io/obj-deserializer/tests/translate.test.js
Yup. Another one... sigh
These changes add V2 require and export statements to the translated script. Test suites also updated.
> V2 : Fix OBJ Deserializer

- packages/cli/cli.js
- packages/cli/src/determineOutputNameAndFormat.js
- packages/cli/src/parseArgs.js
- packages/core/io/formats.js
These are some minor fixes to the CLI, as not all supported formats were enabled.
Also, an additional error message is logged if a project entry point is not found.
> V2 : Fixes to CLI

- README.md
- package.json
- packages/examples/package.json
These changes enable lint via standard JS (standardjs.com)
NOTE: No code changes are being made as cleanup can be done piece by piece by those with energy.
> V2: Enable lint

- packages/modeling/src/color/color.js
- packages/modeling/src/color/hslToRgb.js
- packages/modeling/src/color/hslToRgb.test.js
- packages/modeling/src/color/hsvToRgb.js
- packages/modeling/src/color/hsvToRgb.test.js
- packages/modeling/src/color/rgbToHex.js
- packages/modeling/src/color/rgbToHex.test.js
- packages/modeling/src/color/rgbToHsl.js
- packages/modeling/src/color/rgbToHsl.test.js
- packages/modeling/src/color/rgbToHsv.js
- packages/modeling/src/color/rgbToHsv.test.js
These changes enchance the conversion functions to use spread parameters, allowing the functions to accept both arrays of values or a list of values.
In addition, a few adjustments to doc strings were made.
> V2 : cleanup color api

- V2-changes.md
This adds a slightly modified and cleaned up version of the list of changes present in the wiki, for multiple reasons:
- simply text
- accessible offline
- is shipped with the repo/ can be included in the app etc 
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
> docs(V2): added a markdown, cleaned up list of V2 changes

- packages/io/stl-serializer/CSGToStlb.js
> V2 : Update CSGToStlb.js

- packages/modeling/src/math/mat4/clone.js
Missing variable declaration causing failure in strict mode.
> V2: Missing variable declaration

- packages/io/svg-deserializer/tests/instantiate.test.js
Fixes small errors in the tests (likely error in last merge)
> tests(svg-deserializer): Fix svg deserializer tests

- packages/modeling/src/colors/colorize.js
- packages/modeling/src/colors/colorize.test.js
- packages/vtree/core/index.js
These are quick patches to changes for color => colorize, making the requested change in pull request #591 
There's also a fix for colorze() for path2, which was identifed when testing.
> V2 : patch colors

- packages/io/amf-deserializer/objectBuilder.js
- packages/io/amf-deserializer/translate.js
- packages/io/dxf-deserializer/translate.js
- packages/io/svg-deserializer/index.js
- packages/vtree/core/generators/geometry-generator-cached-csg.js
These changes contain addition patches to complete the name change of 'color' to 'colors'.
In addition to the automated test suite, I performed manual tests for the conversion of all external formats, both deserialize and serialize.
> V2 : additional patches for color to colors name change

- packages/utils/regl-renderer/README.md
- packages/utils/regl-renderer/demo-cli.js
- packages/utils/regl-renderer/demo-web.js
- packages/utils/regl-renderer/package.json
- packages/utils/regl-renderer/src/bound-utils/boundingBox.js
- packages/utils/regl-renderer/src/bound-utils/boundingSphere.js
- packages/utils/regl-renderer/src/bound-utils/computeBounds.js
- packages/utils/regl-renderer/src/bound-utils/computeBounds.test.js
- packages/utils/regl-renderer/src/cameras/camera.js
- packages/utils/regl-renderer/src/cameras/orthographicCamera.js
- packages/utils/regl-renderer/src/controls/elementSizing.js
- packages/utils/regl-renderer/src/controls/orbitControls.js
- packages/utils/regl-renderer/src/geometry-utils-V2/entitiesFromSolids.js
- packages/utils/regl-renderer/src/geometry-utils-V2/geom2ToGeometries.js
- packages/utils/regl-renderer/src/geometry-utils-V2/geom3ToGeometries.js
- packages/utils/regl-renderer/src/geometry-utils-V2/path2ToGeometries.js
- packages/utils/regl-renderer/src/geometry-utils/cagToGeometries.js
- packages/utils/regl-renderer/src/geometry-utils/csgToGeometries.js
- packages/utils/regl-renderer/src/geometry-utils/entitiesFromSolids.js
- packages/utils/regl-renderer/src/rendering/commands/drawExps/drawConnector/arcGeo.js
- packages/utils/regl-renderer/src/rendering/commands/drawExps/drawConnector/index.js
- packages/utils/regl-renderer/src/rendering/commands/drawExps/drawMesh.js
- packages/utils/regl-renderer/src/rendering/commands/drawExps/drawMeshNoNormals.js
- packages/utils/regl-renderer/src/rendering/commands/drawExps/drawNormals.js
- packages/utils/regl-renderer/src/rendering/commands/drawExps/drawNormals2.js
- packages/utils/regl-renderer/src/rendering/commands/drawMesh/index.js
- packages/utils/regl-renderer/src/rendering/render.js
- packages/utils/regl-renderer/src/rendering/renderContext.js
- packages/utils/regl-renderer/src/utils.js
These changes move the REGL renderer to V2, including the demo applications.
There are also two small fixes:
- implemented an alternate cache for render, removing the use of JSON
- corrected entitiesFromSolids to use the params passed
There are also lots of small changes as the code is now beautiful. :)
> V2 : enhance regl renderer

- packages/web/data/theme.dark.json
- packages/web/data/theme.grass.json
- packages/web/data/theme.light.json
- packages/web/data/theme.ocean.json
- packages/web/data/themes.js
- packages/web/demo.css
- packages/web/src/ui/flow/themes.js
- packages/web/src/ui/views/io.js
- packages/web/src/ui/views/main.js
- packages/web/src/ui/views/options.js
- packages/web/src/ui/views/parameterControls.js
- packages/web/src/ui/views/toolbar.js
- packages/web/src/ui/views/viewer.js
These changes address two issues.
- enhance themes
- enhance layout to address issues with Safari
The theme loading has been enhanced, and now works properly across all browsers. In addition, two new themes have been added; grass and ocean.
The HTML layout of the 'header' has been changed to use DIV and SPAN entities. This allows the page to work with Safari, and other browsers.
Fixes #364 
Fixes #321
> V2 : enhance themes

- README.md
- package.json
- packages/web/src/sideEffects/localFs/index.js
- packages/web/src/sideEffects/localFs/walkFileTree.js
- packages/web/src/ui/flow/design.js
- packages/web/src/ui/flow/exports.js
- packages/web/src/ui/views/io.js
These changes contain two different fixes/enhancements.
- fix selection of export formats, and export of selected format
- enhance project load from directories, converting flat file list to file hiearchy, which can then be used like drag-n-drop 
Fixes #508
> V2 : fix project loading from directories

- packages/web/demo.css
- packages/web/locales/de.json
- packages/web/locales/en.json
- packages/web/locales/fr.json
- packages/web/locales/ja.json
- packages/web/src/ui/views/help.js
These changes update the help for the WEB UI.
- correcting links to online documentation and forums
- adding multiple language support for help
> V2 : WEB enhance help

- packages/core/parameters/applyParameterDefinitions.js
- packages/core/parameters/getParameterValuesFromUIControls.js
- packages/web/demo.css
- packages/web/src/ui/flow/design.js
- packages/web/src/ui/views/parameterControls.js
Addresses a variety of issues with parameters:
- Choice parameters without captions now work.
- Groups can now be defaulted to closed.
- Groups don't re-open when another parameter is changed.
- Slider parameters now respect the min/max attributes.
```
const {primitives} = require('@jscad/modeling')
const values = [3,4,5,6]
const captions = ["three","four","five","six"]
const getParameterDefinitions = () => {
return [
{name: 'group1', type: 'group', caption: 'Group 1: Text Entry'},
{name: 'text', type: 'text', initial: '', size: 20, maxLength: 20, caption: 'Plain Text:', placeholder: '20 characters'},
{name: 'int', type: 'int', initial: 20, min: 1, max: 100, step: 1, caption: 'Integer:'},
{name: 'number', type: 'number', initial: 2.0, min: 1.0, max: 10.0, step: 0.1, caption: 'Number:'}, …
```
> V2 fix web params

- packages/modeling/src/primitives/torus.js
- packages/modeling/src/primitives/torus.test.js
Reversed the order of applied transforms, updated test to catch similar issues.
> fix unwanted offset when outerRotation applied

- .gitignore
Adding working folders to the .gitignore file for the new docs folder location, and the .idea IDE temp folder
* [ x] Have you followed the guidelines in our Contributing document?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ x] Does your submission pass tests?
> chore(all): housekeeping on gitignore file

- lerna.json
- packages/most-gestures/.gitignore
- packages/most-gestures/.npmrc
- packages/most-gestures/.travis.yml
- packages/most-gestures/LICENSE
- packages/most-gestures/README.md
- packages/most-gestures/package.json
- packages/most-gestures/src/drags.js
- packages/most-gestures/src/gestures.test.js
- packages/most-gestures/src/index.js
- packages/most-gestures/src/presses.js
- packages/most-gestures/src/taps.js
- packages/most-gestures/src/utils.js
- packages/most-gestures/src/zooms.js
- packages/web/src/ui/views/viewer.js
These changes enable multi-gesture touch events for mobile devices.
Sadly, a new package was added, most-gestures, as a bug fix to this package was required. This should be a temporary fix until this package has been updated.
Testing ws performed on several PCs, iPad, Android mobile.
> V2 : enable multi-gesture touch events for mobile devices

- jsdoc.json
- packages/modeling/src/index.js
Removing connectors for the time being until we can make them actually work.
> fix(core): Remove connectors from public api

- packages/web/src/ui/views/viewer.js
changed rotate and pan to use requestAnimationFrame (removed need for cancelAnimationFrame I used in my first attempt at this)
this change also works well when dev console is active in chrome (V1 and V2 on chrome with dev console slow down the rotation significantly )
> V2 rotate/pan throttling change proposal

- packages/utils/regl-renderer/src/cameras/camera.js
- packages/utils/regl-renderer/src/controls/orbitControls.js
- packages/web/css/demo.css
- packages/web/src/ui/flow/actionTypes.js
- packages/web/src/ui/flow/design.js
- packages/web/src/ui/flow/shortcuts.js
- packages/web/src/ui/flow/viewer.js
- packages/web/src/ui/views/io.js
- packages/web/src/ui/views/shortcuts.js
- packages/web/src/ui/views/viewer.js
- packages/web/src/ui/views/viewerControls.js
These changes correct the WEB UI to support keyboard shortcuts, as well as activation of auto-rotate.
Fixes #700 
Fixes #235
> V2 : fix keyboard shortcuts and activation of auto-rotate

- packages/modeling/src/maths/line2/fromPoints.js
- packages/modeling/src/maths/line3/fromPoints.js
- packages/modeling/src/operations/transforms/align.js
- packages/modeling/src/primitives/cylinder.js
- packages/modeling/src/primitives/cylinderElliptic.js
i believe these are supposed to be numbers, not vector3's. :smiley_cat:
> V2 : document changes

- packages/web/demo.html
- packages/web/locales/de.json
- packages/web/locales/en.json
- packages/web/locales/fr.json
- packages/web/src/ui/flow/design.js
- packages/web/src/ui/views/parameterControls.js
These changes fix the internal processing for auto-updates.
In addition, there were some changes to:
- add a title to the demo (main) page
- added translations for 'reset'
- code cleanup
Fixes #742
> V2 fix instant update

- packages/modeling/src/operations/booleans/trees/Node.js
- packages/modeling/src/operations/booleans/trees/PolygonTreeNode.js
- packages/modeling/src/operations/booleans/trees/Tree.js
As the title says... just refactoring to create proper classes.
> refactor(modeling): refactored boolean trees into ES5 classes

- packages/core/src/sideEffects/i18n/index.js
- packages/desktop/README.md
- packages/web/locales/de.json
- packages/web/locales/en.json
- packages/web/locales/fr.json
- packages/web/locales/hr.json
- packages/web/locales/ja.json
- packages/web/src/index.js
> hr translations

- packages/web/locales/de.json
- packages/web/locales/en.json
- packages/web/locales/fr.json
- packages/web/locales/ja.json
- packages/web/src/ui/flow/viewer.js
- packages/web/src/ui/views/options.js
- packages/web/src/ui/views/viewer.js
- packages/web/src/ui/views/viewerControls.js
These changes enhance the WEB UI to support auto zoom. The changes are:
- create auto zoom control (and remove zoom options)
- update most streams to support setting of auto zoom control
- update view to support auto zoom control
- update locales for languages
> feat(web): enhanced to support auto zoom control

- packages/utils/regl-renderer/demo-cli.js
- packages/utils/regl-renderer/demo-web.js
- packages/utils/regl-renderer/demo.html
- packages/utils/regl-renderer/src/geometry-utils-V2/entitiesFromSolids.test.js
- packages/utils/regl-renderer/src/geometry-utils-V2/geom2ToGeometries.js
- packages/utils/regl-renderer/src/geometry-utils-V2/geom2ToGeometries.test.js
- packages/utils/regl-renderer/src/geometry-utils-V2/path2ToGeometries.js
- packages/utils/regl-renderer/src/geometry-utils-V2/path2ToGeometries.test.js
- packages/utils/regl-renderer/src/rendering/commands/drawGrid/index.js
- packages/utils/regl-renderer/src/rendering/commands/drawGrid/multi.js
- packages/utils/regl-renderer/src/rendering/render.js
DO NOT SQUASH MERGE
The following fixes are included:
- corrected conversions of empty solids to entities
- added reasonable defaults to drawGrid
- corrected to render entities by default
- added comments to demos
Testing was performed with:
- WEB UI
- cli version of regl-renderer
- demo.html of regl-renderer
- dev version of regl-renderer
> Fixes to regl-renderer

- packages/examples/core/other/orientation.js
- packages/examples/core/primitives/sphere.js
- packages/examples/core/text/text.js
- packages/examples/parameters/balloons.js
Several fixes for the examples. And one new example for orientation.
> Fix examples

- packages/web/src/ui/views/viewer.js
render needs to be called after window resize
> Fix render onresize

- packages/utils/regl-renderer/demo.html
added more gestures support for demo, to be more like openjscad in that regard
- rotate now only on drag
- pan with shift
- zoom on scroll or pinch on touchpad (if browser fake the wheel)
I am looking at the demo to play with web workers, but wanted to improve the demo a bit first.
> Improve regl render demo

- packages/utils/regl-renderer/package.json
seems to be working fine. If it is really ok, it will be smaller step if they implement webgl2
(@z3dev unfortunately, the latest version of regl is also just webgl1)
> bump regl version to 2.1.0

- README.md
- jsdoc.json
- jsdoc/assets/README.md
- jsdoc/tutorials/01_gettingStarted.md
- packages/cli/README.md
- packages/io/amf-deserializer/index.js
- packages/io/amf-serializer/index.js
- packages/io/json-serializer/README.md
- packages/modeling/src/curves/bezier/create.js
- packages/modeling/src/curves/bezier/tangentAt.js
- packages/modeling/src/curves/bezier/valueAt.js
- packages/modeling/src/measurements/measureArea.js
- packages/modeling/src/measurements/measureBoundingBox.js
- packages/modeling/src/measurements/measureEpsilon.js
- packages/modeling/src/measurements/measureVolume.js
- packages/modeling/src/operations/expansions/offset.js
- packages/modeling/src/operations/extrusions/project.js
- packages/modeling/src/operations/modifiers/generalize.js
- packages/modeling/src/operations/modifiers/snap.js
- packages/web/locales/ja.json
- packages/web/src/ui/views/help.js
A few documentation changes to correct some issues.
Also, new information links were added to the help of the WEB UI
- open issues
- discord community
> Document changes

- packages/core/package.json
- packages/web/package.json
> fix(core): fix 917 missing json5 dependency

- packages/modeling/src/measurements/measureBoundingBox.js
- packages/web/src/ui/views/viewer.js
See the commit comments for the fixes.
Manually tested the web ui fix with normal and super large designs.
> Quick fixes for modeling and web ui

- packages/core/src/code-loading/webRequire.js
- packages/core/src/code-loading/webRequire.test.js
> feat(web): add caching to webRequire

- packages/modeling/src/colors/hslToRgb.js
- packages/modeling/src/colors/hueToColorComponent.js
- packages/modeling/src/curves/bezier/tangentAt.js
- packages/modeling/src/geometries/geom3/invert.js
- packages/modeling/src/geometries/geom3/toPoints.js
- packages/modeling/src/operations/extrusions/extrudeLinear.js
- packages/modeling/src/operations/modifiers/generalize.js
- packages/modeling/src/operations/transforms/mirror.js
- packages/modeling/src/primitives/roundedCylinder.js
> docs(modeling): doc changes from user reviews

- packages/modeling/src/operations/booleans/trees/Node.js
- packages/modeling/src/operations/booleans/trees/PolygonTreeNode.js
- packages/modeling/src/operations/booleans/trees/Tree.js
- packages/modeling/src/operations/booleans/trees/splitPolygonByPlane.js
There are changes from my deep dives into the BSP trees. Most of the changes are just style changes, but there are a few small logic changes. Hopefully, these make life easier for the next developer.
> style(modeling): small changes from deep dives into the BSP trees

- packages/modeling/src/operations/modifiers/reTesselateCoplanarPolygons.js
These changes improve the performance of reTesselateCoplanarPolygons, which is used by the boolean operations underneath to optimize the polygon meshes.
I always have major issues with this code but here are some more changes. Hopefully, this improves the performance of the boolean operations. TO BE SEEN
FYI, there's about 97% coverage on this function via the test suites.
> perf(modeling): improved performance of reTesselateCoplanarPolygons by using maps or sets

- packages/web/src/sideEffects/worker/index.js
While working through some issues with rollup, I came across issues with the webworkify package. (It can only be packaged using Browserify. 😢  ) However, I tried to retain the webworker instead of terminating / initializing. It works just fine across the browsers. In addition. error handling has been improved so processing should be more robust as well.
Performance improves differently across the browsers, but basically the 100 ms delay of creating a new webworker is gone.
Manually tested these changes across Safari, Firefox, Chrome, and Edge on MacOS 10.14.6
Also Safari, Firefox, Chrome, and Edge on IOS
> perf(web): changed to retain webworker process

- packages/modeling/src/operations/modifiers/insertTjunctions.js
Followup from #1051
This PR replaces js objects `{}` with faster `Map` in insertTjunctions. There is a measurable speed improvement depending on the model. For `generalize` applied to two unioned spheres, this results in improvements:
- generalize: 188ms -> 96ms
- insertTjunctions (step1): 32ms -> 32ms
- insertTjunctions (step2): 3ms -> 2ms
- insertTjunctions (step3): 150ms -> 57ms
```js
const jscad = require('@jscad/modeling')
const { union } = jscad.booleans
const { sphere } = jscad.primitives
const { generalize } = jscad.modifiers
const segments = 100
const main = () => {
let out = union(sphere({ segments }), sphere({ segments, center: [1, 0, 0] }))
const startTime = performance.now()
out = generalize({ triangulate: true }, out)
console.log(`Generalize time ${performance.now() - …
```
> perf(modeling): convert {} to Map in insertTjunctions

- packages/modeling/src/index.d.ts
> Export modifiers for TypeScript

- packages/web/locales/README.md
- packages/web/locales/de.json
- packages/web/locales/fr.json
- packages/web/locales/hr.json
- packages/web/locales/ja.json
- packages/web/src/index.js
- packages/web/src/sideEffects/i18n/index.js
These changes enable the new Chinese locale in the WEB UI. Also, the other locales were updated to add a language specific selection for 'Chinese' as well.
> Enable Chinese locale

- README.md
- packages/cli/README.md
- packages/core/README.md
- packages/examples/README.md
- packages/io/amf-deserializer/README.md
- packages/io/amf-serializer/README.md
- packages/io/dxf-deserializer/README.md
- packages/io/dxf-serializer/README.md
- packages/io/io-utils/README.md
- packages/io/io/README.md
- packages/io/json-deserializer/README.md
- packages/io/json-serializer/README.md
- packages/io/obj-deserializer/README.md
- packages/io/obj-serializer/README.md
- packages/io/stl-deserializer/README.md
- packages/io/stl-serializer/README.md
- packages/io/svg-deserializer/README.md
- packages/io/svg-serializer/README.md
- packages/io/x3d-deserializer/README.md
- packages/io/x3d-serializer/README.md
- packages/modeling/README.md
- packages/modeling/src/operations/extrusions/slice/index.js
- packages/utils/array-utils/README.md
- packages/utils/regl-renderer/README.md
- packages/vtree/README.md
- packages/web/README.md
> docs(all): corrections to README files, additional docs for slice

- packages/modeling/src/primitives/cuboid.js
- packages/modeling/src/utils/insertSorted.js
> docs(all): fix typos

- packages/utils/regl-renderer/src/geometry-utils-V2/entitiesFromSolids.test.js
- packages/utils/regl-renderer/src/geometry-utils-V2/geom3ToGeometries.js
- packages/utils/regl-renderer/src/geometry-utils-V2/geom3ToGeometries.test.js
- packages/utils/regl-renderer/src/rendering/commands/drawLines/index.js
- packages/utils/regl-renderer/src/rendering/commands/drawMesh/index.js
this fixes #1178 by removing code I added previously for transparent entities
> fix 1178 transparent object overlap solid objects

- V3-CHANGES.md
- packages/modeling/src/geometries/path2/appendArc.js
- packages/modeling/src/geometries/path2/appendArc.test.js
- packages/modeling/src/operations/expansions/extrudePolygon.js
These changes correct names for parameters (options) to follow standards for cameCase.
> fix(modeling): corrected parameter names to follow standards

- packages/io/x3d-serializer/src/index.js
- packages/io/x3d-serializer/tests/geom2ToX3D.test.js
- packages/io/x3d-serializer/tests/geom3ToX3D.test.js
- packages/io/x3d-serializer/tests/path2ToX3D.test.js
addresses partially #1235
also sets X3D version to 3.3 since some printing services check for the version
> X3D serializer: optional smoothing, Y up, X3D version

- packages/io/x3d-serializer/README.md
- packages/io/x3d-serializer/src/index.js
- packages/io/x3d-serializer/tests/geom2ToX3D.test.js
- packages/io/x3d-serializer/tests/geom3ToX3D.test.js
- packages/io/x3d-serializer/tests/path2ToX3D.test.js
Rather subtle improvement to rendering by adding some specular highlighting similar to the default renderer. See #1234.
> x3d-serializer: specular highlights and shape names

- packages/modeling/src/operations/extrusions/index.d.ts
Closes #1260 
Some typing definitions were missing.
Tests pass.
> fix(modeling): add extrudeHelical type definition

- packages/io/svg-deserializer/tests/instantiate.test.js
- packages/io/svg-deserializer/tests/translate.test.js
- packages/io/svg-serializer/index.js
- packages/io/svg-serializer/tests/geom2.test.js
- packages/io/svg-serializer/tests/path2.test.js
> @jscad/svg-serializer: convertColor: fix: opacity output

- packages/utils/regl-renderer/types/controls/orbitControls.d.ts
- packages/utils/regl-renderer/types/geometry-utils-V2/entitiesFromSolids.d.ts
- packages/utils/regl-renderer/types/geometry-utils-V2/entity.d.ts
> Define the entity type

- packages/core/package.json
- packages/examples/package.json
- packages/io/3mf-deserializer/package.json
- packages/io/3mf-serializer/package.json
- packages/io/dxf-deserializer/package.json
- packages/io/dxf-serializer/package.json
- packages/io/json-deserializer/package.json
- packages/io/json-serializer/package.json
- packages/io/obj-deserializer/package.json
- packages/io/obj-serializer/package.json
- packages/io/stl-deserializer/package.json
- packages/io/stl-serializer/package.json
- packages/io/svg-deserializer/package.json
- packages/io/svg-serializer/package.json
- packages/io/x3d-deserializer/package.json
- packages/io/x3d-deserializer/rollup.config.js
- packages/io/x3d-serializer/package.json
- packages/io/x3d-serializer/rollup.config.js
- packages/modeling/package.json
- packages/modeling/rollup.config.js
- packages/utils/array-utils/package.json
- packages/utils/img/package.json
- packages/utils/regl-renderer/package.json
- packages/utils/regl-renderer/rollup.config.js
- packages/vtree/package.json
- packages/web/package.json
These changes update the various packages in preparation for pre-releases of V3. The changes include:
- package changes for distributing UMD and ES libraries
- package changes to create new versions of libraries
- rollup changes to include all dependencies and minify the package
**NOTE: There are no code changes. All tests pass.**
> build(all): changes to packages and rollup in preparation for prerelese

- packages/modeling/src/geometries/geom2/transform.js
- packages/modeling/src/geometries/geom2/transform.test.js
- packages/modeling/src/operations/extrusions/extrudeRotate.js
- packages/modeling/src/operations/transforms/mirror.test.js
Same as #1302 but for master branch. Fixes #1301
> fix(modeling): corrected geom2 mirroring transform

- README.md
Trivial, just noticed it as it is right at the start of the description.
> "hosteable" => "hostable"

- packages/modeling/src/primitives/roundedCuboid.js
- packages/modeling/src/primitives/roundedCylinder.js
- packages/modeling/src/primitives/roundedRectangle.js
Got the error yesterday and spotted the typo
See also #1327
> fix(typo): fix then/than in rounded error messages

- packages/modeling/src/operations/booleans/index.d.ts
- packages/modeling/src/operations/booleans/scission.d.ts
> fix(modeling): create scission.d.ts and update index.d.ts

- packages/io/obj-deserializer/README.md
Previous example code did not work and has been changed to now work.
This is a documentation change and not a code change.
* [ x ] Have you followed the guidelines in our Contributing document?
* [ x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ x ] Does your submission pass tests?
> resolves #1352

- packages/modeling/src/operations/hulls/hull.test.js
- packages/modeling/src/operations/hulls/hullGeom3.js
> fix(modeling): hull of single unconvex solid

- packages/modeling/src/primitives/torus.js
* [ yes] Have you followed the guidelines in our Contributing document?
* [ yes] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ yes] Does your submission pass tests?
> Update torus.js: fix typo (s/two/too)

- CHANGELOG.md
- LICENSE
- jsdoc/assets/README.md
- packages/modeling/src/curves/index.js
- packages/modeling/src/maths/index.js
- packages/modeling/src/operations/booleans/intersect.js
- packages/modeling/src/operations/booleans/scission.js
- packages/modeling/src/operations/booleans/subtract.js
- packages/modeling/src/operations/booleans/union.js
- packages/modeling/src/operations/expansions/expand.js
- packages/modeling/src/operations/extrusions/extrudeHelical.js
- packages/modeling/src/operations/extrusions/index.js
- packages/modeling/src/operations/hulls/index.js
- packages/modeling/src/operations/modifiers/index.js
- packages/modeling/src/operations/modifiers/snap.js
- packages/modeling/src/primitives/arc.js
- packages/modeling/src/primitives/polyhedron.js
- packages/modeling/src/text/vectorChar.js
- packages/modeling/src/text/vectorText.js
- packages/modeling/src/utils/index.js
No logic changes. Only document changes.
> V2 document changes

- packages/web/README.md
* flag -r for copy command (cp -r)
* use # for comment
> make sh code comfortable for copy&paste

- packages/modeling/src/measurements/measureBoundingSphere.js
- packages/modeling/src/operations/booleans/martinez/compareEvents.js
- packages/modeling/src/operations/booleans/martinez/connectEdges.js
- packages/modeling/src/operations/booleans/martinez/contour.js
- packages/modeling/src/operations/booleans/martinez/divideSegment.js
- packages/modeling/src/operations/booleans/martinez/fillQueue.js
- packages/modeling/src/operations/booleans/martinez/index.js
- packages/modeling/src/operations/booleans/martinez/possibleIntersection.js
- packages/modeling/src/operations/booleans/martinez/segmentIntersection.js
- packages/modeling/src/operations/booleans/martinez/splaytree.js
- packages/modeling/src/operations/booleans/martinez/subdivideSegments.js
- packages/modeling/src/operations/booleans/martinez/sweepEvent.js
- packages/modeling/src/operations/booleans/trees/Node.js
- packages/modeling/src/operations/booleans/trees/PolygonTreeNode.js
- packages/modeling/src/operations/booleans/trees/Tree.js
- packages/modeling/src/operations/booleans/trees/splitPolygonByPlane.js
- packages/modeling/src/operations/extrusions/extrudeWalls.js
- packages/modeling/src/operations/hulls/hullPoints2.js
- packages/modeling/src/operations/modifiers/mergePolygons.js
- packages/modeling/src/operations/modifiers/reTesselateCoplanarPolygons.js
Set of changes to improve performance in 2D and 3D boolean libraries, as well as extrusions.
There are also a substantial amount of changes in the martinez library, which was... let's say.. kind of out-of-date / strange code. These changes should help in maintenance, as well as add meaningful test cases (which are missing).
> perf(modeling): changes to improve performance in booleans and extrusions

- packages/io/svg-deserializer/src/shapesMapGeometry.js
- packages/io/svg-deserializer/tests/instantiate.test.js
- packages/modeling/src/operations/extrusions/extrudeHelical.js
- packages/modeling/src/operations/extrusions/extrudeHelical.test.js
The changes to V3 for svg-deserializer were really good, so these have been brought into V2.
And a small fix to extrudeHelix as well.
> fixes for modeling and svg deserializer
